import abjad
import baca


instruments = abjad.InstrumentDictionary([
    (
        'BassClarinet',
        abjad.BassClarinet(suppress_markup=True),
        ),
    (
        'Bassoon',
        abjad.Bassoon(suppress_markup=True),
        ),
    (
        'Cello',
        abjad.Cello(suppress_markup=True),
        ),
    (
        'Clarinet',
        abjad.ClarinetInBFlat(suppress_markup=True),
        ),
    (
        'Contrabass',
        abjad.Contrabass(suppress_markup=True),
        ),
    (
        'EnglishHorn',
        abjad.EnglishHorn(suppress_markup=True),
        ),
    (
        'Flute',
        abjad.Flute(suppress_markup=True),
        ),
    (
        'Harp',
        abjad.Harp(suppress_markup=True),
        ),
    (
        'Horn',
        abjad.FrenchHorn(suppress_markup=True),
        ),
    (
        'Oboe',
        abjad.Oboe(suppress_markup=True),
        ),
    (
        'Percussion',
        abjad.Percussion(suppress_markup=True),
        ),
    (
        'Piano',
        abjad.Piano(suppress_markup=True),
        ),
    (
        'Piccolo',
        abjad.Piccolo(suppress_markup=True),
        ),
    (
        'Trombone',
        abjad.TenorTrombone(suppress_markup=True),
        ),
    (
        'Trumpet',
        abjad.Trumpet(suppress_markup=True),
        ),
    (
        'Tuba',
        abjad.Tuba(suppress_markup=True),
        ),
    (
        'Viola',
        abjad.Viola(suppress_markup=True),
        ),
    (
        'Violin',
        abjad.Violin(suppress_markup=True),
        ),
    ])
