import abjad
import baca


instruments = abjad.InstrumentDictionary([
    (
        'BassClarinet',
        abjad.BassClarinet(suppress=True),
        ),
    (
        'Bassoon',
        abjad.Bassoon(suppress=True),
        ),
    (
        'Cello',
        abjad.Cello(suppress=True),
        ),
    (
        'Clarinet',
        abjad.ClarinetInBFlat(suppress=True),
        ),
    (
        'Contrabass',
        abjad.Contrabass(suppress=True),
        ),
    (
        'EnglishHorn',
        abjad.EnglishHorn(suppress=True),
        ),
    (
        'Flute',
        abjad.Flute(suppress=True),
        ),
    (
        'Harp',
        abjad.Harp(suppress=True),
        ),
    (
        'Horn',
        abjad.FrenchHorn(suppress=True),
        ),
    (
        'Oboe',
        abjad.Oboe(suppress=True),
        ),
    (
        'Percussion',
        abjad.Percussion(suppress=True),
        ),
    (
        'Piano',
        abjad.Piano(suppress=True),
        ),
    (
        'Piccolo',
        abjad.Piccolo(suppress=True),
        ),
    (
        'Trombone',
        abjad.TenorTrombone(suppress=True),
        ),
    (
        'Trumpet',
        abjad.Trumpet(suppress=True),
        ),
    (
        'Tuba',
        abjad.Tuba(suppress=True),
        ),
    (
        'Viola',
        abjad.Viola(suppress=True),
        ),
    (
        'Violin',
        abjad.Violin(suppress=True),
        ),
    ])
