import abjad


metadata = abjad.OrderedDict(
    [
        (
            'alive_during_segment',
            [
                'Score',
                'Global_Context',
                'Global_Rests',
                'Global_Skips',
                'Music_Context',
                'Wind_Staff_Group',
                'OboeFamily_Square_Staff_Group',
                'Oboe_Staff_I',
                'Oboe_Voice_I',
                'Oboe_Rest_Voice_I',
                'English_Horn_Staff_I',
                'English_Horn_Voice_I',
                'English_Horn_Rest_Voice_I',
                'Bassoon_Staff_I',
                'Bassoon_Voice_I',
                'Bassoon_Rest_Voice_I',
                'Bassoon_Voice_II',
                'Bassoon_Rest_Voice_II',
                'String_Staff_Group',
                'FirstViolin_Square_Staff_Group',
                'First_Violin_Staff_I',
                'First_Violin_Voice_I',
                'First_Violin_Rest_Voice_I',
                'First_Violin_Voice_II',
                'First_Violin_Rest_Voice_II',
                'First_Violin_Staff_II',
                'First_Violin_Voice_III',
                'First_Violin_Rest_Voice_III',
                'First_Violin_Voice_IV',
                'First_Violin_Rest_Voice_IV',
                'First_Violin_Staff_III',
                'First_Violin_Voice_V',
                'SecondViolin_Square_Staff_Group',
                'Second_Violin_Staff_I',
                'Second_Violin_Voice_I',
                'Second_Violin_Rest_Voice_I',
                'Second_Violin_Voice_II',
                'Second_Violin_Rest_Voice_II',
                'Second_Violin_Staff_II',
                'Second_Violin_Voice_III',
                'Second_Violin_Rest_Voice_III',
                'Second_Violin_Voice_IV',
                'Second_Violin_Rest_Voice_IV',
                'Viola_Square_Staff_Group',
                'Viola_Staff_I',
                'Viola_Voice_I',
                'Viola_Rest_Voice_I',
                'Viola_Voice_II',
                'Viola_Rest_Voice_II',
                'Viola_Staff_II',
                'Viola_Voice_III',
                'Viola_Rest_Voice_III',
                'Viola_Voice_IV',
                'Viola_Rest_Voice_IV',
                'Cello_Staff_I',
                'Cello_Voice_I',
                'Cello_Rest_Voice_I',
                'Cello_Voice_II',
                'Cello_Rest_Voice_II',
                'Contrabass_Staff_II',
                'Contrabass_Voice_III',
                'Contrabass_Rest_Voice_III',
                ],
            ),
        (
            'bol_measure_numbers',
            [95],
            ),
        ('duration', "0'24''"),
        ('final_measure_number', 108),
        (
            'first_appearance_margin_markup',
            abjad.OrderedDict(
                [
                    ('Bassoon_Staff_I', 'Bsn.'),
                    ('English_Horn_Staff_I', 'Eng. hn.'),
                    ('First_Violin_Staff_III', 'Vni. I 18'),
                    ('Oboe_Staff_I', 'Ob.'),
                    ]
                ),
            ),
        ('first_measure_number', 95),
        ('segment_name', 'O'),
        ('segment_number', 16),
        ('start_clock_time', "3'10''"),
        ('stop_clock_time', "3'34''"),
        (
            'time_signatures',
            [
                '3/4',
                '3/4',
                '4/4',
                '4/4',
                '4/4',
                '3/4',
                '3/4',
                '4/4',
                '4/4',
                '2/4',
                '3/4',
                '3/4',
                '4/4',
                '2/4',
                ],
            ),
        ]
    )
