import abjad


metadata = abjad.OrderedDict(
    [
        (
            'alive_during_segment',
            [
                'Score',
                'Global_Context',
                'Global_Rests',
                'Global_Skips',
                'Music_Context',
                'Wind_Staff_Group',
                'Clarinet_Staff_I',
                'Clarinet_Voice_I',
                'Clarinet_Rest_Voice_I',
                'Brass_Staff_Group',
                'Horn_Square_Staff_Group',
                'Horn_Staff_I',
                'Horn_Voice_I',
                'Horn_Rest_Voice_I',
                'Horn_Voice_III',
                'Horn_Rest_Voice_III',
                'Horn_Staff_II',
                'Horn_Voice_II',
                'Horn_Rest_Voice_II',
                'Horn_Voice_IV',
                'Horn_Rest_Voice_IV',
                'Trumpet_Square_Staff_Group',
                'Trumpet_Staff_I',
                'Trumpet_Voice_I',
                'Trumpet_Rest_Voice_I',
                'Trumpet_Voice_III',
                'Trumpet_Rest_Voice_III',
                'Trumpet_Staff_II',
                'Trumpet_Voice_II',
                'Trumpet_Rest_Voice_II',
                'Trumpet_Voice_IV',
                'Trumpet_Rest_Voice_IV',
                'Trombone_Square_Staff_Group',
                'Trombone_Staff_I',
                'Trombone_Voice_I',
                'Trombone_Rest_Voice_I',
                'Trombone_Voice_III',
                'Trombone_Rest_Voice_III',
                'Trombone_Staff_II',
                'Trombone_Voice_II',
                'Trombone_Rest_Voice_II',
                'Trombone_Voice_IV',
                'Trombone_Rest_Voice_IV',
                'Tuba_Staff_I',
                'Tuba_Voice_I',
                'Tuba_Rest_Voice_I',
                'Percussion_Staff_Group',
                'Percussion_Staff_I',
                'Percussion_Voice_I',
                'Percussion_Rest_Voice_I',
                'Percussion_Staff_II',
                'Percussion_Voice_II',
                'Percussion_Rest_Voice_II',
                'String_Staff_Group',
                'FirstViolin_Square_Staff_Group',
                'First_Violin_Staff_I',
                'First_Violin_Voice_II',
                'First_Violin_Rest_Voice_II',
                'First_Violin_Voice_I',
                'First_Violin_Staff_II',
                'First_Violin_Voice_III',
                'SecondViolin_Square_Staff_Group',
                'Second_Violin_Staff_I',
                'Second_Violin_Voice_I',
                'Second_Violin_Staff_II',
                'Second_Violin_Voice_III',
                'Viola_Square_Staff_Group',
                'Viola_Staff_I',
                'Viola_Voice_I',
                'Viola_Staff_II',
                'Viola_Voice_III',
                'Cello_Staff_I',
                'Cello_Voice_I',
                'Contrabass_Staff_II',
                'Contrabass_Voice_III',
                'Contrabass_Rest_Voice_III',
                ],
            ),
        (
            'bol_measure_numbers',
            [18],
            ),
        ('duration', "0'12''"),
        ('final_measure_number', 23),
        (
            'first_appearance_margin_markup',
            abjad.OrderedDict(
                [
                    ('Clarinet_Staff_I', 'Cl. 3'),
                    ('Contrabass_Staff_II', 'Cb.'),
                    ('Horn_Staff_I', 'Hn. (1+3)'),
                    ('Horn_Staff_II', 'Hn. (2+4)'),
                    ('Trombone_Staff_I', 'Trb. (1+3)'),
                    ('Trombone_Staff_II', 'Trb. (2+4)'),
                    ('Trumpet_Staff_I', 'Tp. (1+3)'),
                    ('Trumpet_Staff_II', 'Tp. (2+4)'),
                    ('Tuba_Staff_I', 'Tub.'),
                    ]
                ),
            ),
        ('first_measure_number', 18),
        ('segment_name', 'C'),
        ('segment_number', 4),
        ('start_clock_time', "0'29''"),
        ('stop_clock_time', "0'41''"),
        (
            'time_signatures',
            ['4/4', '4/4', '4/4', '4/4', '4/4', '3/4'],
            ),
        ]
    )
