import abjad


metadata = abjad.OrderedDict(
    [
        (
            'alive_during_segment',
            [
                'Score',
                'GlobalContext',
                'GlobalRests',
                'GlobalSkips',
                'MusicContext',
                'WindStaffGroup',
                'ClarinetStaffI',
                'ClarinetVoiceI',
                'PianoPianoStaff',
                'PianoStaffI',
                'PianoVoiceI',
                'HarpPianoStaff',
                'HarpStaffI',
                'HarpVoiceI',
                'PercussionStaffGroup',
                'PercussionStaffI',
                'PercussionVoiceI',
                'PercussionStaffII',
                'PercussionVoiceII',
                'PercussionStaffIII',
                'PercussionVoiceIII',
                'StringStaffGroup',
                'FirstViolinStaffI',
                'FirstViolinVoiceI',
                'SecondViolinStaffI',
                'SecondViolinVoiceI',
                'ViolaStaffI',
                'ViolaVoiceI',
                'CelloStaffI',
                'CelloVoiceI',
                'ContrabassSquareStaffGroup',
                'ContrabassStaffI',
                'ContrabassVoiceI',
                'ContrabassStaffII',
                'ContrabassVoiceIII',
                ],
            ),
        (
            'bol_measure_numbers',
            [36],
            ),
        (
            'container_to_part_assignment',
            abjad.OrderedDict(
                [
                    (
                        'C_CelloVoiceI_a',
                        (
                            abjad.PartAssignment('Cello'),
                            abjad.Timespan(
                                start_offset=abjad.Offset(0, 1),
                                stop_offset=abjad.Offset(7, 1),
                                ),
                            ),
                        ),
                    (
                        'C_ClarinetVoiceI_a',
                        (
                            abjad.PartAssignment('Clarinet', 1),
                            abjad.Timespan(
                                start_offset=abjad.Offset(0, 1),
                                stop_offset=abjad.Offset(7, 2),
                                ),
                            ),
                        ),
                    (
                        'C_ClarinetVoiceI_b',
                        (
                            abjad.PartAssignment('Clarinet', 2),
                            abjad.Timespan(
                                start_offset=abjad.Offset(7, 2),
                                stop_offset=abjad.Offset(7, 1),
                                ),
                            ),
                        ),
                    (
                        'C_ContrabassVoiceIII_a',
                        (
                            abjad.PartAssignment('Contrabass', (2, 6)),
                            abjad.Timespan(
                                start_offset=abjad.Offset(0, 1),
                                stop_offset=abjad.Offset(7, 1),
                                ),
                            ),
                        ),
                    (
                        'C_ContrabassVoiceI_a',
                        (
                            abjad.PartAssignment('Contrabass', 1),
                            abjad.Timespan(
                                start_offset=abjad.Offset(0, 1),
                                stop_offset=abjad.Offset(7, 1),
                                ),
                            ),
                        ),
                    (
                        'C_FirstViolinVoiceI_a',
                        (
                            abjad.PartAssignment('FirstViolin'),
                            abjad.Timespan(
                                start_offset=abjad.Offset(0, 1),
                                stop_offset=abjad.Offset(7, 1),
                                ),
                            ),
                        ),
                    (
                        'C_HarpVoiceI_a',
                        (
                            abjad.PartAssignment('Harp'),
                            abjad.Timespan(
                                start_offset=abjad.Offset(0, 1),
                                stop_offset=abjad.Offset(7, 1),
                                ),
                            ),
                        ),
                    (
                        'C_PercussionVoiceIII_a',
                        (
                            abjad.PartAssignment('Percussion', 3),
                            abjad.Timespan(
                                start_offset=abjad.Offset(0, 1),
                                stop_offset=abjad.Offset(7, 1),
                                ),
                            ),
                        ),
                    (
                        'C_PercussionVoiceII_a',
                        (
                            abjad.PartAssignment('Percussion', 2),
                            abjad.Timespan(
                                start_offset=abjad.Offset(0, 1),
                                stop_offset=abjad.Offset(7, 1),
                                ),
                            ),
                        ),
                    (
                        'C_PercussionVoiceI_a',
                        (
                            abjad.PartAssignment('Percussion', 1),
                            abjad.Timespan(
                                start_offset=abjad.Offset(0, 1),
                                stop_offset=abjad.Offset(7, 1),
                                ),
                            ),
                        ),
                    (
                        'C_PianoVoiceI_a',
                        (
                            abjad.PartAssignment('Piano'),
                            abjad.Timespan(
                                start_offset=abjad.Offset(0, 1),
                                stop_offset=abjad.Offset(7, 1),
                                ),
                            ),
                        ),
                    (
                        'C_SecondViolinVoiceI_a',
                        (
                            abjad.PartAssignment('SecondViolin'),
                            abjad.Timespan(
                                start_offset=abjad.Offset(0, 1),
                                stop_offset=abjad.Offset(7, 1),
                                ),
                            ),
                        ),
                    (
                        'C_ViolaVoiceI_a',
                        (
                            abjad.PartAssignment('Viola'),
                            abjad.Timespan(
                                start_offset=abjad.Offset(0, 1),
                                stop_offset=abjad.Offset(7, 1),
                                ),
                            ),
                        ),
                    ]
                ),
            ),
        ('duration', "0'22''"),
        (
            'first_appearance_margin_markup',
            abjad.OrderedDict(
                [
                    ('ContrabassStaffI', 'Cb. 1'),
                    ('HarpStaffI', 'Hp.'),
                    ('PercussionStaffIII', 'Perc. 3 (vib.)'),
                    ('PianoStaffI', 'Pf.'),
                    ]
                ),
            ),
        ('first_measure_number', 36),
        ('last_measure_number', 43),
        (
            'persistent_indicators',
            abjad.OrderedDict(
                [
                    (
                        'CelloStaffI',
                        [
                            abjad.Momento(
                                context='CelloVoiceI',
                                prototype='abjad.Clef',
                                value='bass',
                                ),
                            abjad.Momento(
                                context='CelloVoiceI',
                                prototype='abjad.Instrument',
                                value='Cello',
                                ),
                            abjad.Momento(
                                context='CelloVoiceI',
                                prototype='abjad.MarginMarkup',
                                value='Vc.',
                                ),
                            ],
                        ),
                    (
                        'CelloVoiceI',
                        [
                            abjad.Momento(
                                context='CelloVoiceI',
                                prototype='abjad.Dynamic',
                                value='pp',
                                ),
                            ],
                        ),
                    (
                        'ClarinetStaffI',
                        [
                            abjad.Momento(
                                context='ClarinetVoiceI',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='ClarinetVoiceI',
                                prototype='abjad.Instrument',
                                value='Clarinet',
                                ),
                            abjad.Momento(
                                context='ClarinetVoiceI',
                                prototype='abjad.MarginMarkup',
                                value='Cl. 2',
                                ),
                            ],
                        ),
                    (
                        'ClarinetVoiceI',
                        [
                            abjad.Momento(
                                context='ClarinetVoiceI',
                                prototype='abjad.Dynamic',
                                value='mf',
                                ),
                            ],
                        ),
                    (
                        'ContrabassStaffI',
                        [
                            abjad.Momento(
                                context='ContrabassVoiceI',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='ContrabassVoiceI',
                                prototype='abjad.Instrument',
                                value='Contrabass',
                                ),
                            abjad.Momento(
                                context='ContrabassVoiceI',
                                prototype='abjad.MarginMarkup',
                                value='Cb. 1',
                                ),
                            ],
                        ),
                    (
                        'ContrabassStaffII',
                        [
                            abjad.Momento(
                                context='ContrabassVoiceIII',
                                prototype='abjad.Clef',
                                value='bass',
                                ),
                            abjad.Momento(
                                context='ContrabassVoiceIII',
                                prototype='abjad.Instrument',
                                value='Contrabass',
                                ),
                            abjad.Momento(
                                context='ContrabassVoiceIII',
                                prototype='abjad.MarginMarkup',
                                value='Cb. (2-6)',
                                ),
                            ],
                        ),
                    (
                        'ContrabassVoiceI',
                        [
                            abjad.Momento(
                                context='ContrabassVoiceI',
                                prototype='abjad.Dynamic',
                                value='mf',
                                ),
                            ],
                        ),
                    (
                        'ContrabassVoiceIII',
                        [
                            abjad.Momento(
                                context='ContrabassVoiceIII',
                                prototype='abjad.Dynamic',
                                value='p',
                                ),
                            ],
                        ),
                    (
                        'FirstViolinStaffI',
                        [
                            abjad.Momento(
                                context='FirstViolinVoiceI',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='FirstViolinVoiceI',
                                prototype='abjad.Instrument',
                                value='Violin',
                                ),
                            abjad.Momento(
                                context='FirstViolinVoiceI',
                                prototype='abjad.MarginMarkup',
                                value='Vni. I',
                                ),
                            ],
                        ),
                    (
                        'FirstViolinStaffII',
                        [
                            abjad.Momento(
                                context='FirstViolinVoiceIII',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='FirstViolinVoiceIII',
                                prototype='abjad.Instrument',
                                value='Violin',
                                ),
                            abjad.Momento(
                                context='FirstViolinVoiceIII',
                                prototype='abjad.MarginMarkup',
                                value='Vni. I (11-18)',
                                ),
                            ],
                        ),
                    (
                        'FirstViolinVoiceI',
                        [
                            abjad.Momento(
                                context='FirstViolinVoiceI',
                                prototype='abjad.Dynamic',
                                value='pp',
                                ),
                            ],
                        ),
                    (
                        'FirstViolinVoiceII',
                        [
                            abjad.Momento(
                                context='FirstViolinVoiceII',
                                prototype='abjad.Dynamic',
                                value='p',
                                ),
                            ],
                        ),
                    (
                        'FirstViolinVoiceIII',
                        [
                            abjad.Momento(
                                context='FirstViolinVoiceIII',
                                prototype='abjad.Dynamic',
                                value='\\f_but_accents_sffz',
                                ),
                            ],
                        ),
                    (
                        'HarpPianoStaff',
                        [
                            abjad.Momento(
                                context='HarpVoiceI',
                                prototype='abjad.Instrument',
                                value='Harp',
                                ),
                            ],
                        ),
                    (
                        'HarpStaffI',
                        [
                            abjad.Momento(
                                context='HarpVoiceI',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='HarpVoiceI',
                                prototype='abjad.MarginMarkup',
                                value='Hp.',
                                ),
                            ],
                        ),
                    (
                        'HarpVoiceI',
                        [
                            abjad.Momento(
                                context='HarpVoiceI',
                                prototype='abjad.Dynamic',
                                value='mf',
                                ),
                            ],
                        ),
                    (
                        'HornStaffI',
                        [
                            abjad.Momento(
                                context='HornVoiceI',
                                prototype='abjad.Clef',
                                value='bass',
                                ),
                            abjad.Momento(
                                context='HornVoiceIII',
                                prototype='abjad.Instrument',
                                value='Horn',
                                ),
                            abjad.Momento(
                                context='HornVoiceI',
                                prototype='abjad.MarginMarkup',
                                value='Hn. (1+3)',
                                ),
                            ],
                        ),
                    (
                        'HornStaffII',
                        [
                            abjad.Momento(
                                context='HornVoiceII',
                                prototype='abjad.Clef',
                                value='bass',
                                ),
                            abjad.Momento(
                                context='HornVoiceIV',
                                prototype='abjad.Instrument',
                                value='Horn',
                                ),
                            abjad.Momento(
                                context='HornVoiceII',
                                prototype='abjad.MarginMarkup',
                                value='Hn. (2+4)',
                                ),
                            ],
                        ),
                    (
                        'HornVoiceI',
                        [
                            abjad.Momento(
                                context='HornVoiceI',
                                prototype='abjad.Dynamic',
                                value='sffz',
                                ),
                            ],
                        ),
                    (
                        'HornVoiceII',
                        [
                            abjad.Momento(
                                context='HornVoiceII',
                                prototype='abjad.Dynamic',
                                value='sffz',
                                ),
                            ],
                        ),
                    (
                        'HornVoiceIII',
                        [
                            abjad.Momento(
                                context='HornVoiceIII',
                                edition=abjad.Tag('+PARTS'),
                                prototype='abjad.Dynamic',
                                value='sffz',
                                ),
                            ],
                        ),
                    (
                        'HornVoiceIV',
                        [
                            abjad.Momento(
                                context='HornVoiceIV',
                                edition=abjad.Tag('+PARTS'),
                                prototype='abjad.Dynamic',
                                value='sffz',
                                ),
                            ],
                        ),
                    (
                        'PercussionStaffI',
                        [
                            abjad.Momento(
                                context='PercussionVoiceI',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceI',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceI',
                                prototype='abjad.MarginMarkup',
                                value='Perc. 1 (tri.)',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceI',
                                prototype='abjad.PersistentOverride',
                                value=abjad.PersistentOverride(
                                    after=True,
                                    attribute='bar_extent',
                                    context='Staff',
                                    grob='bar_line',
                                    value=(0, 0),
                                    ),
                                ),
                            abjad.Momento(
                                context='PercussionVoiceI',
                                prototype='baca.StaffLines',
                                value=1,
                                ),
                            ],
                        ),
                    (
                        'PercussionStaffII',
                        [
                            abjad.Momento(
                                context='PercussionVoiceII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceII',
                                prototype='abjad.MarginMarkup',
                                value='Perc. 2 (cym.)',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceII',
                                prototype='abjad.PersistentOverride',
                                value=abjad.PersistentOverride(
                                    after=True,
                                    attribute='bar_extent',
                                    context='Staff',
                                    grob='bar_line',
                                    value=(0, 0),
                                    ),
                                ),
                            abjad.Momento(
                                context='PercussionVoiceII',
                                prototype='baca.StaffLines',
                                value=1,
                                ),
                            ],
                        ),
                    (
                        'PercussionStaffIII',
                        [
                            abjad.Momento(
                                context='PercussionVoiceIII',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceIII',
                                prototype='abjad.Instrument',
                                value='Vibraphone',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceIII',
                                prototype='abjad.MarginMarkup',
                                value='Perc. 3 (vib.)',
                                ),
                            ],
                        ),
                    (
                        'PercussionVoiceI',
                        [
                            abjad.Momento(
                                context='PercussionVoiceI',
                                prototype='abjad.Dynamic',
                                value='niente',
                                ),
                            ],
                        ),
                    (
                        'PercussionVoiceII',
                        [
                            abjad.Momento(
                                context='PercussionVoiceII',
                                prototype='abjad.Dynamic',
                                value='p',
                                ),
                            ],
                        ),
                    (
                        'PercussionVoiceIII',
                        [
                            abjad.Momento(
                                context='PercussionVoiceIII',
                                prototype='abjad.Dynamic',
                                value='mp',
                                ),
                            ],
                        ),
                    (
                        'PianoPianoStaff',
                        [
                            abjad.Momento(
                                context='PianoVoiceI',
                                prototype='abjad.Instrument',
                                value='Piano',
                                ),
                            ],
                        ),
                    (
                        'PianoStaffI',
                        [
                            abjad.Momento(
                                context='PianoVoiceI',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='PianoVoiceI',
                                prototype='abjad.MarginMarkup',
                                value='Pf.',
                                ),
                            ],
                        ),
                    (
                        'PianoVoiceI',
                        [
                            abjad.Momento(
                                context='PianoVoiceI',
                                prototype='abjad.Dynamic',
                                value='mf',
                                ),
                            ],
                        ),
                    (
                        'Score',
                        [
                            abjad.Momento(
                                context='GlobalSkips',
                                prototype='abjad.MetronomeMark',
                                value='76',
                                ),
                            abjad.Momento(
                                context='GlobalSkips',
                                prototype='abjad.TimeSignature',
                                value='4/4',
                                ),
                            ],
                        ),
                    (
                        'SecondViolinStaffI',
                        [
                            abjad.Momento(
                                context='SecondViolinVoiceI',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='SecondViolinVoiceI',
                                prototype='abjad.Instrument',
                                value='Violin',
                                ),
                            abjad.Momento(
                                context='SecondViolinVoiceI',
                                prototype='abjad.MarginMarkup',
                                value='Vni. II',
                                ),
                            ],
                        ),
                    (
                        'SecondViolinStaffII',
                        [
                            abjad.Momento(
                                context='SecondViolinVoiceIII',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='SecondViolinVoiceIII',
                                prototype='abjad.Instrument',
                                value='Violin',
                                ),
                            abjad.Momento(
                                context='SecondViolinVoiceIII',
                                prototype='abjad.MarginMarkup',
                                value='Vni. II (11-18)',
                                ),
                            ],
                        ),
                    (
                        'SecondViolinVoiceI',
                        [
                            abjad.Momento(
                                context='SecondViolinVoiceI',
                                prototype='abjad.Dynamic',
                                value='pp',
                                ),
                            ],
                        ),
                    (
                        'SecondViolinVoiceIII',
                        [
                            abjad.Momento(
                                context='SecondViolinVoiceIII',
                                prototype='abjad.Dynamic',
                                value='\\f_but_accents_sffz',
                                ),
                            ],
                        ),
                    (
                        'TromboneStaffI',
                        [
                            abjad.Momento(
                                context='TromboneVoiceI',
                                prototype='abjad.Clef',
                                value='tenor',
                                ),
                            abjad.Momento(
                                context='TromboneVoiceIII',
                                prototype='abjad.Instrument',
                                value='Trombone',
                                ),
                            abjad.Momento(
                                context='TromboneVoiceI',
                                prototype='abjad.MarginMarkup',
                                value='Trb. (1+3)',
                                ),
                            ],
                        ),
                    (
                        'TromboneStaffII',
                        [
                            abjad.Momento(
                                context='TromboneVoiceII',
                                prototype='abjad.Clef',
                                value='tenor',
                                ),
                            abjad.Momento(
                                context='TromboneVoiceIV',
                                prototype='abjad.Instrument',
                                value='Trombone',
                                ),
                            abjad.Momento(
                                context='TromboneVoiceII',
                                prototype='abjad.MarginMarkup',
                                value='Trb. (2+4)',
                                ),
                            ],
                        ),
                    (
                        'TromboneVoiceI',
                        [
                            abjad.Momento(
                                context='TromboneVoiceI',
                                prototype='abjad.Dynamic',
                                value='sffz',
                                ),
                            ],
                        ),
                    (
                        'TromboneVoiceII',
                        [
                            abjad.Momento(
                                context='TromboneVoiceII',
                                prototype='abjad.Dynamic',
                                value='sffz',
                                ),
                            ],
                        ),
                    (
                        'TromboneVoiceIII',
                        [
                            abjad.Momento(
                                context='TromboneVoiceIII',
                                edition=abjad.Tag('+PARTS'),
                                prototype='abjad.Dynamic',
                                value='sffz',
                                ),
                            ],
                        ),
                    (
                        'TromboneVoiceIV',
                        [
                            abjad.Momento(
                                context='TromboneVoiceIV',
                                edition=abjad.Tag('+PARTS'),
                                prototype='abjad.Dynamic',
                                value='sffz',
                                ),
                            ],
                        ),
                    (
                        'TrumpetStaffI',
                        [
                            abjad.Momento(
                                context='TrumpetVoiceI',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='TrumpetVoiceIII',
                                prototype='abjad.Instrument',
                                value='Trumpet',
                                ),
                            abjad.Momento(
                                context='TrumpetVoiceI',
                                prototype='abjad.MarginMarkup',
                                value='Tp. (1+3)',
                                ),
                            ],
                        ),
                    (
                        'TrumpetStaffII',
                        [
                            abjad.Momento(
                                context='TrumpetVoiceII',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='TrumpetVoiceIV',
                                prototype='abjad.Instrument',
                                value='Trumpet',
                                ),
                            abjad.Momento(
                                context='TrumpetVoiceII',
                                prototype='abjad.MarginMarkup',
                                value='Tp. (2+4)',
                                ),
                            ],
                        ),
                    (
                        'TrumpetVoiceI',
                        [
                            abjad.Momento(
                                context='TrumpetVoiceI',
                                prototype='abjad.Dynamic',
                                value='sffz',
                                ),
                            ],
                        ),
                    (
                        'TrumpetVoiceII',
                        [
                            abjad.Momento(
                                context='TrumpetVoiceII',
                                prototype='abjad.Dynamic',
                                value='sffz',
                                ),
                            ],
                        ),
                    (
                        'TrumpetVoiceIII',
                        [
                            abjad.Momento(
                                context='TrumpetVoiceIII',
                                edition=abjad.Tag('+PARTS'),
                                prototype='abjad.Dynamic',
                                value='sffz',
                                ),
                            ],
                        ),
                    (
                        'TrumpetVoiceIV',
                        [
                            abjad.Momento(
                                context='TrumpetVoiceIV',
                                edition=abjad.Tag('+PARTS'),
                                prototype='abjad.Dynamic',
                                value='sffz',
                                ),
                            ],
                        ),
                    (
                        'TubaStaffI',
                        [
                            abjad.Momento(
                                context='TubaVoiceI',
                                prototype='abjad.Clef',
                                value='bass',
                                ),
                            abjad.Momento(
                                context='TubaVoiceI',
                                prototype='abjad.Instrument',
                                value='Tuba',
                                ),
                            abjad.Momento(
                                context='TubaVoiceI',
                                prototype='abjad.MarginMarkup',
                                value='Tub.',
                                ),
                            ],
                        ),
                    (
                        'TubaVoiceI',
                        [
                            abjad.Momento(
                                context='TubaVoiceI',
                                prototype='abjad.Dynamic',
                                value='sffz',
                                ),
                            ],
                        ),
                    (
                        'ViolaStaffI',
                        [
                            abjad.Momento(
                                context='ViolaVoiceI',
                                prototype='abjad.Clef',
                                value='alto',
                                ),
                            abjad.Momento(
                                context='ViolaVoiceI',
                                prototype='abjad.Instrument',
                                value='Viola',
                                ),
                            abjad.Momento(
                                context='ViolaVoiceI',
                                prototype='abjad.MarginMarkup',
                                value='Vle.',
                                ),
                            ],
                        ),
                    (
                        'ViolaStaffII',
                        [
                            abjad.Momento(
                                context='ViolaVoiceIII',
                                prototype='abjad.Clef',
                                value='alto',
                                ),
                            abjad.Momento(
                                context='ViolaVoiceIII',
                                prototype='abjad.Instrument',
                                value='Viola',
                                ),
                            abjad.Momento(
                                context='ViolaVoiceIII',
                                prototype='abjad.MarginMarkup',
                                value='Vle. (11-18)',
                                ),
                            ],
                        ),
                    (
                        'ViolaVoiceI',
                        [
                            abjad.Momento(
                                context='ViolaVoiceI',
                                prototype='abjad.Dynamic',
                                value='pp',
                                ),
                            ],
                        ),
                    (
                        'ViolaVoiceIII',
                        [
                            abjad.Momento(
                                context='ViolaVoiceIII',
                                prototype='abjad.Dynamic',
                                value='\\f_but_accents_sffz',
                                ),
                            ],
                        ),
                    ]
                ),
            ),
        ('segment_name', 'C'),
        ('segment_number', 7),
        (
            'sounds_during_segment',
            abjad.OrderedDict(
                [
                    ('CelloVoiceI', True),
                    ('ClarinetVoiceI', True),
                    ('ContrabassVoiceI', True),
                    ('ContrabassVoiceIII', True),
                    ('FirstViolinVoiceI', True),
                    ('HarpVoiceI', True),
                    ('PercussionVoiceI', False),
                    ('PercussionVoiceII', True),
                    ('PercussionVoiceIII', True),
                    ('PianoVoiceI', True),
                    ('SecondViolinVoiceI', True),
                    ('ViolaVoiceI', True),
                    ]
                ),
            ),
        ('start_clock_time', "1'04''"),
        ('stop_clock_time', "1'26''"),
        (
            'time_signatures',
            [
                '2/4',
                '4/4',
                '4/4',
                '4/4',
                '4/4',
                '2/4',
                '4/4',
                '4/4',
                ],
            ),
        (
            'voice_metadata',
            abjad.OrderedDict(
                [
                    (
                        'ContrabassVoiceI',
                        abjad.OrderedDict(
                            [
                                (
                                    'RHYTHM',
                                    abjad.OrderedDict(
                                        [
                                            ('divisions_consumed', 28),
                                            ('logical_ties_produced', 30),
                                            ('name', 'harp_exchange_rhythm'),
                                            ('talea_weight_consumed', 168),
                                            ]
                                        ),
                                    ),
                                ]
                            ),
                        ),
                    (
                        'HarpVoiceI',
                        abjad.OrderedDict(
                            [
                                (
                                    'RHYTHM',
                                    abjad.OrderedDict(
                                        [
                                            ('divisions_consumed', 28),
                                            ('logical_ties_produced', 27),
                                            ('name', 'harp_exchange_rhythm'),
                                            ('talea_weight_consumed', 168),
                                            ]
                                        ),
                                    ),
                                ]
                            ),
                        ),
                    (
                        'PercussionVoiceIII',
                        abjad.OrderedDict(
                            [
                                (
                                    'RHYTHM',
                                    abjad.OrderedDict(
                                        [
                                            ('divisions_consumed', 28),
                                            ('logical_ties_produced', 31),
                                            ('name', 'harp_exchange_rhythm'),
                                            ('talea_weight_consumed', 168),
                                            ]
                                        ),
                                    ),
                                ]
                            ),
                        ),
                    (
                        'PianoVoiceI',
                        abjad.OrderedDict(
                            [
                                (
                                    'RHYTHM',
                                    abjad.OrderedDict(
                                        [
                                            ('divisions_consumed', 28),
                                            ('logical_ties_produced', 27),
                                            ('name', 'harp_exchange_rhythm'),
                                            ('talea_weight_consumed', 168),
                                            ]
                                        ),
                                    ),
                                ]
                            ),
                        ),
                    ]
                ),
            ),
        ]
    )
