import abjad


metadata = abjad.OrderedDict(
    [
        (
            'alive_during_segment',
            [
                'Score',
                'Global_Context',
                'Global_Rests',
                'Global_Skips',
                'Music_Context',
                'Wind_Staff_Group',
                'Clarinet_Staff_I',
                'Clarinet_Voice_I',
                'Bass_Clarinet_Staff_I',
                'Bass_Clarinet_Voice_I',
                'Bass_Clarinet_Rest_Voice_I',
                'Brass_Staff_Group',
                'Horn_Square_Staff_Group',
                'Horn_Staff_I',
                'Horn_Voice_I',
                'Horn_Voice_III',
                'Horn_Staff_II',
                'Horn_Voice_II',
                'Horn_Voice_IV',
                'Trumpet_Square_Staff_Group',
                'Trumpet_Staff_I',
                'Trumpet_Voice_I',
                'Trumpet_Voice_III',
                'Trumpet_Staff_II',
                'Trumpet_Voice_II',
                'Trumpet_Voice_IV',
                'Trombone_Square_Staff_Group',
                'Trombone_Staff_I',
                'Trombone_Voice_I',
                'Trombone_Voice_III',
                'Trombone_Staff_II',
                'Trombone_Voice_II',
                'Trombone_Voice_IV',
                'Piano_Piano_Staff',
                'Piano_Staff_I',
                'Piano_Voice_I',
                'Harp_Piano_Staff',
                'Harp_Staff_I',
                'Harp_Voice_I',
                'Percussion_Staff_Group',
                'Percussion_Staff_II',
                'Percussion_Voice_II',
                'Percussion_Staff_III',
                'Percussion_Voice_III',
                'String_Staff_Group',
                'First_Violin_Staff_I',
                'First_Violin_Voice_I',
                'Second_Violin_Staff_I',
                'Second_Violin_Voice_I',
                'Viola_Staff_I',
                'Viola_Voice_I',
                'Cello_Staff_I',
                'Cello_Voice_I',
                'Contrabass_Square_Staff_Group',
                'Contrabass_Staff_I',
                'Contrabass_Voice_I',
                'Contrabass_Staff_II',
                'Contrabass_Voice_III',
                ],
            ),
        (
            'bol_measure_numbers',
            [56],
            ),
        ('duration', "0'09''"),
        ('final_measure_number', 61),
        ('first_measure_number', 56),
        ('segment_name', 'I'),
        ('segment_number', 10),
        ('start_clock_time', "1'50''"),
        ('stop_clock_time', "1'59''"),
        (
            'time_signatures',
            ['2/4', '3/4', '3/4', '4/4', '2/4', '4/4'],
            ),
        ]
    )
