import abjad
import ide

persist = abjad.OrderedDict(
    [
        (
            "alive_during_segment",
            [
                "Score",
                "Global_Context",
                "Global_Rests",
                "Global_Skips",
                "Music_Context",
                "Piano_Piano_Staff",
                "Piano_Staff_I",
                "Piano_Voice_I",
                "Piano_Rest_Voice_I",
                "Percussion_Staff_Group",
                "Percussion_Staff_IV",
                "Percussion_Voice_IV",
                "Percussion_Rest_Voice_IV",
            ],
        ),
        (
            "container_to_part_assignment",
            abjad.OrderedDict(
                [
                    (
                        "ad_Percussion_Voice_IV_a",
                        (
                            ide.PartAssignment("Percussion", 4),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((33, 4)),
                            ),
                        ),
                    ),
                    (
                        "ad_Piano_Voice_I_a",
                        (
                            ide.PartAssignment("Piano"),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((33, 4)),
                            ),
                        ),
                    ),
                ]
            ),
        ),
        (
            "persistent_indicators",
            abjad.OrderedDict(
                [
                    (
                        "Bass_Clarinet_Staff_I",
                        [
                            ide.Momento(
                                context="Bass_Clarinet_Voice_I",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="B. cl.",
                            ),
                            ide.Momento(
                                context="Bass_Clarinet_Voice_I",
                                manifest="instruments",
                                value="BassClarinet",
                            ),
                            ide.Momento(
                                context="Bass_Clarinet_Voice_I",
                                prototype="abjad.Clef",
                                value="treble",
                            ),
                        ],
                    ),
                    (
                        "Bass_Clarinet_Voice_I",
                        [
                            ide.Momento(
                                context="Bass_Clarinet_Voice_I",
                                prototype="abjad.Dynamic",
                                value="p",
                            ),
                        ],
                    ),
                    (
                        "Bassoon_Staff_I",
                        [
                            ide.Momento(
                                context="Bassoon_Voice_I",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Bsn.",
                            ),
                            ide.Momento(
                                context="Bassoon_Voice_I",
                                manifest="instruments",
                                value="Bassoon",
                            ),
                            ide.Momento(
                                context="Bassoon_Voice_I",
                                prototype="abjad.Clef",
                                value="bass",
                            ),
                        ],
                    ),
                    (
                        "Bassoon_Voice_I",
                        [
                            ide.Momento(
                                context="Bassoon_Voice_I",
                                edition=abjad.Tag("+PARTS"),
                                prototype="abjad.Dynamic",
                                value="niente",
                            ),
                        ],
                    ),
                    (
                        "Bassoon_Voice_II",
                        [
                            ide.Momento(
                                context="Bassoon_Voice_II",
                                prototype="abjad.Dynamic",
                                value="niente",
                            ),
                        ],
                    ),
                    (
                        "Cello_Staff_I",
                        [
                            ide.Momento(
                                context="Cello_Voice_I",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vc. (1-2)",
                            ),
                            ide.Momento(
                                context="Cello_Voice_I",
                                manifest="instruments",
                                value="Cello",
                            ),
                            ide.Momento(
                                context="Cello_Voice_II",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="Cello_Voice_II",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="Cello_Voice_II",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "Cello_Staff_II",
                        [
                            ide.Momento(
                                context="Cello_Voice_III",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vc. (3-4)",
                            ),
                            ide.Momento(
                                context="Cello_Voice_III",
                                manifest="instruments",
                                value="Cello",
                            ),
                            ide.Momento(
                                context="Cello_Voice_IV",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="Cello_Voice_IV",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="Cello_Voice_IV",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "Cello_Staff_III",
                        [
                            ide.Momento(
                                context="Cello_Voice_V",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vc. (5-6)",
                            ),
                            ide.Momento(
                                context="Cello_Voice_V",
                                manifest="instruments",
                                value="Cello",
                            ),
                            ide.Momento(
                                context="Cello_Voice_VI",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="Cello_Voice_VI",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="Cello_Voice_VI",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "Cello_Staff_IV",
                        [
                            ide.Momento(
                                context="Cello_Voice_VII",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vc. (7-8)",
                            ),
                            ide.Momento(
                                context="Cello_Voice_VII",
                                manifest="instruments",
                                value="Cello",
                            ),
                            ide.Momento(
                                context="Cello_Voice_VIII",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="Cello_Voice_VIII",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="Cello_Voice_VIII",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "Cello_Staff_V",
                        [
                            ide.Momento(
                                context="Cello_Voice_IX",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vc. (9-10)",
                            ),
                            ide.Momento(
                                context="Cello_Voice_IX",
                                manifest="instruments",
                                value="Cello",
                            ),
                            ide.Momento(
                                context="Cello_Voice_X",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="Cello_Voice_X",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="Cello_Voice_X",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "Cello_Staff_VI",
                        [
                            ide.Momento(
                                context="Cello_Voice_XI",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vc. (11-12)",
                            ),
                            ide.Momento(
                                context="Cello_Voice_XI",
                                manifest="instruments",
                                value="Cello",
                            ),
                            ide.Momento(
                                context="Cello_Voice_XII",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="Cello_Voice_XII",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="Cello_Voice_XII",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "Cello_Staff_VII",
                        [
                            ide.Momento(
                                context="Cello_Voice_XIII",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vc. (13-14)",
                            ),
                            ide.Momento(
                                context="Cello_Voice_XIII",
                                manifest="instruments",
                                value="Cello",
                            ),
                            ide.Momento(
                                context="Cello_Voice_XIV",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="Cello_Voice_XIV",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="Cello_Voice_XIV",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "Cello_Voice_I",
                        [
                            ide.Momento(
                                context="Cello_Voice_I",
                                prototype="abjad.Dynamic",
                                value="niente",
                            ),
                        ],
                    ),
                    (
                        "Cello_Voice_II",
                        [
                            ide.Momento(
                                context="Cello_Voice_II",
                                prototype="abjad.Dynamic",
                                value="niente",
                            ),
                        ],
                    ),
                    (
                        "Clarinet_Staff_I",
                        [
                            ide.Momento(
                                context="Clarinet_Voice_I",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Cl. 1",
                            ),
                            ide.Momento(
                                context="Clarinet_Voice_I",
                                manifest="instruments",
                                value="Clarinet",
                            ),
                            ide.Momento(
                                context="Clarinet_Voice_I",
                                prototype="abjad.Clef",
                                value="treble",
                            ),
                        ],
                    ),
                    (
                        "Clarinet_Voice_I",
                        [
                            ide.Momento(
                                context="Clarinet_Voice_I",
                                prototype="abjad.Dynamic",
                                value="ff",
                            ),
                        ],
                    ),
                    (
                        "Contrabass_Staff_I",
                        [
                            ide.Momento(
                                context="Contrabass_Voice_I",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Cb. (1-2)",
                            ),
                            ide.Momento(
                                context="Contrabass_Voice_I",
                                manifest="instruments",
                                value="Contrabass",
                            ),
                            ide.Momento(
                                context="Contrabass_Voice_II",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="Contrabass_Voice_II",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="Contrabass_Voice_II",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "Contrabass_Staff_II",
                        [
                            ide.Momento(
                                context="Contrabass_Voice_III",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Cb. (3-4)",
                            ),
                            ide.Momento(
                                context="Contrabass_Voice_III",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=5,
                            ),
                            ide.Momento(
                                context="Contrabass_Voice_III",
                                manifest="instruments",
                                value="Contrabass",
                            ),
                            ide.Momento(
                                context="Contrabass_Voice_III",
                                prototype="abjad.Clef",
                                value="bass",
                            ),
                            ide.Momento(
                                context="Contrabass_Voice_III",
                                prototype="baca.StaffLines",
                                value=5,
                            ),
                        ],
                    ),
                    (
                        "Contrabass_Staff_III",
                        [
                            ide.Momento(
                                context="Contrabass_Voice_V",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Cb. (5-6)",
                            ),
                            ide.Momento(
                                context="Contrabass_Voice_V",
                                manifest="instruments",
                                value="Contrabass",
                            ),
                            ide.Momento(
                                context="Contrabass_Voice_VI",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="Contrabass_Voice_VI",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="Contrabass_Voice_VI",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "Contrabass_Voice_I",
                        [
                            ide.Momento(
                                context="Contrabass_Voice_I",
                                prototype="abjad.Dynamic",
                                value="mf",
                            ),
                        ],
                    ),
                    (
                        "Contrabass_Voice_III",
                        [
                            ide.Momento(
                                context="Contrabass_Voice_III",
                                prototype="abjad.Dynamic",
                                value="fff",
                            ),
                        ],
                    ),
                    (
                        "English_Horn_Staff_I",
                        [
                            ide.Momento(
                                context="English_Horn_Voice_I",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Eng. hn.",
                            ),
                            ide.Momento(
                                context="English_Horn_Voice_I",
                                manifest="instruments",
                                value="EnglishHorn",
                            ),
                            ide.Momento(
                                context="English_Horn_Voice_I",
                                prototype="abjad.Clef",
                                value="treble",
                            ),
                        ],
                    ),
                    (
                        "English_Horn_Voice_I",
                        [
                            ide.Momento(
                                context="English_Horn_Voice_I",
                                prototype="abjad.Dynamic",
                                value="niente",
                            ),
                        ],
                    ),
                    (
                        "First_Violin_Staff_I",
                        [
                            ide.Momento(
                                context="First_Violin_Voice_I",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vni. I (1-2)",
                            ),
                            ide.Momento(
                                context="First_Violin_Voice_I",
                                manifest="instruments",
                                value="Violin",
                            ),
                            ide.Momento(
                                context="First_Violin_Voice_II",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="First_Violin_Voice_II",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="First_Violin_Voice_II",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "First_Violin_Staff_II",
                        [
                            ide.Momento(
                                context="First_Violin_Voice_III",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vni. I (3-4)",
                            ),
                            ide.Momento(
                                context="First_Violin_Voice_III",
                                manifest="instruments",
                                value="Violin",
                            ),
                            ide.Momento(
                                context="First_Violin_Voice_IV",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="First_Violin_Voice_IV",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="First_Violin_Voice_IV",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "First_Violin_Staff_III",
                        [
                            ide.Momento(
                                context="First_Violin_Voice_V",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vni. I (5-6)",
                            ),
                            ide.Momento(
                                context="First_Violin_Voice_V",
                                manifest="instruments",
                                value="Violin",
                            ),
                            ide.Momento(
                                context="First_Violin_Voice_VI",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="First_Violin_Voice_VI",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="First_Violin_Voice_VI",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "First_Violin_Staff_IV",
                        [
                            ide.Momento(
                                context="First_Violin_Voice_VII",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vni. I (7-8)",
                            ),
                            ide.Momento(
                                context="First_Violin_Voice_VII",
                                manifest="instruments",
                                value="Violin",
                            ),
                            ide.Momento(
                                context="First_Violin_Voice_VIII",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="First_Violin_Voice_VIII",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="First_Violin_Voice_VIII",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "First_Violin_Staff_IX",
                        [
                            ide.Momento(
                                context="First_Violin_Voice_XVII",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vni. I (17-18)",
                            ),
                            ide.Momento(
                                context="First_Violin_Voice_XVII",
                                manifest="instruments",
                                value="Violin",
                            ),
                            ide.Momento(
                                context="First_Violin_Voice_XVIII",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="First_Violin_Voice_XVIII",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="First_Violin_Voice_XVIII",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "First_Violin_Staff_V",
                        [
                            ide.Momento(
                                context="First_Violin_Voice_IX",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vni. I (9-10)",
                            ),
                            ide.Momento(
                                context="First_Violin_Voice_IX",
                                manifest="instruments",
                                value="Violin",
                            ),
                            ide.Momento(
                                context="First_Violin_Voice_X",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="First_Violin_Voice_X",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="First_Violin_Voice_X",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "First_Violin_Staff_VI",
                        [
                            ide.Momento(
                                context="First_Violin_Voice_XI",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vni. I (11-12)",
                            ),
                            ide.Momento(
                                context="First_Violin_Voice_XI",
                                manifest="instruments",
                                value="Violin",
                            ),
                            ide.Momento(
                                context="First_Violin_Voice_XII",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="First_Violin_Voice_XII",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="First_Violin_Voice_XII",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "First_Violin_Staff_VII",
                        [
                            ide.Momento(
                                context="First_Violin_Voice_XIII",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vni. I (13-14)",
                            ),
                            ide.Momento(
                                context="First_Violin_Voice_XIII",
                                manifest="instruments",
                                value="Violin",
                            ),
                            ide.Momento(
                                context="First_Violin_Voice_XIV",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="First_Violin_Voice_XIV",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="First_Violin_Voice_XIV",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "First_Violin_Staff_VIII",
                        [
                            ide.Momento(
                                context="First_Violin_Voice_XV",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vni. I (15-16)",
                            ),
                            ide.Momento(
                                context="First_Violin_Voice_XV",
                                manifest="instruments",
                                value="Violin",
                            ),
                            ide.Momento(
                                context="First_Violin_Voice_XVI",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="First_Violin_Voice_XVI",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="First_Violin_Voice_XVI",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "First_Violin_Voice_I",
                        [
                            ide.Momento(
                                context="First_Violin_Voice_I",
                                prototype="abjad.Dynamic",
                                value="niente",
                            ),
                        ],
                    ),
                    (
                        "First_Violin_Voice_II",
                        [
                            ide.Momento(
                                context="First_Violin_Voice_II",
                                prototype="abjad.Dynamic",
                                value="niente",
                            ),
                        ],
                    ),
                    (
                        "First_Violin_Voice_III",
                        [
                            ide.Momento(
                                context="First_Violin_Voice_III",
                                prototype="abjad.Dynamic",
                                value="niente",
                            ),
                        ],
                    ),
                    (
                        "First_Violin_Voice_IV",
                        [
                            ide.Momento(
                                context="First_Violin_Voice_IV",
                                prototype="abjad.Dynamic",
                                value="niente",
                            ),
                        ],
                    ),
                    (
                        "First_Violin_Voice_V",
                        [
                            ide.Momento(
                                context="First_Violin_Voice_V",
                                prototype="abjad.Dynamic",
                                value="f",
                            ),
                        ],
                    ),
                    (
                        "Flute_Staff_I",
                        [
                            ide.Momento(
                                context="Flute_Voice_I",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Fl. (1+3)",
                            ),
                            ide.Momento(
                                context="Flute_Voice_I",
                                manifest="instruments",
                                value="Flute",
                            ),
                            ide.Momento(
                                context="Flute_Voice_I",
                                prototype="abjad.Clef",
                                value="treble",
                            ),
                        ],
                    ),
                    (
                        "Flute_Staff_II",
                        [
                            ide.Momento(
                                context="Flute_Voice_II",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Fl. (2+4)",
                            ),
                            ide.Momento(
                                context="Flute_Voice_II",
                                manifest="instruments",
                                value="Flute",
                            ),
                            ide.Momento(
                                context="Flute_Voice_II",
                                prototype="abjad.Clef",
                                value="treble",
                            ),
                        ],
                    ),
                    (
                        "Flute_Voice_I",
                        [
                            ide.Momento(
                                context="Flute_Voice_I",
                                edition=abjad.Tag("+PARTS"),
                                prototype="abjad.Dynamic",
                                value="ff",
                            ),
                        ],
                    ),
                    (
                        "Flute_Voice_II",
                        [
                            ide.Momento(
                                context="Flute_Voice_II",
                                edition=abjad.Tag("+PARTS"),
                                prototype="abjad.Dynamic",
                                value="ff",
                            ),
                        ],
                    ),
                    (
                        "Flute_Voice_III",
                        [
                            ide.Momento(
                                context="Flute_Voice_III",
                                prototype="abjad.Dynamic",
                                value="ff",
                            ),
                        ],
                    ),
                    (
                        "Flute_Voice_IV",
                        [
                            ide.Momento(
                                context="Flute_Voice_IV",
                                prototype="abjad.Dynamic",
                                value="ff",
                            ),
                        ],
                    ),
                    (
                        "Harp_Piano_Staff",
                        [
                            ide.Momento(
                                context="Harp_Voice_I",
                                manifest="instruments",
                                value="Harp",
                            ),
                        ],
                    ),
                    (
                        "Harp_Staff_I",
                        [
                            ide.Momento(
                                context="Harp_Voice_I",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Hp.",
                            ),
                            ide.Momento(
                                context="Harp_Voice_I",
                                prototype="abjad.Clef",
                                value="treble",
                            ),
                        ],
                    ),
                    (
                        "Harp_Voice_I",
                        [
                            ide.Momento(
                                context="Harp_Voice_I",
                                prototype="abjad.Dynamic",
                                value="mf",
                            ),
                        ],
                    ),
                    (
                        "Horn_Staff_I",
                        [
                            ide.Momento(
                                context="Horn_Voice_I",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Hn. (1+3)",
                            ),
                            ide.Momento(
                                context="Horn_Voice_I",
                                manifest="instruments",
                                value="Horn",
                            ),
                            ide.Momento(
                                context="Horn_Voice_I",
                                prototype="abjad.Clef",
                                value="bass",
                            ),
                        ],
                    ),
                    (
                        "Horn_Staff_II",
                        [
                            ide.Momento(
                                context="Horn_Voice_II",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Hn. (2+4)",
                            ),
                            ide.Momento(
                                context="Horn_Voice_II",
                                manifest="instruments",
                                value="Horn",
                            ),
                            ide.Momento(
                                context="Horn_Voice_II",
                                prototype="abjad.Clef",
                                value="bass",
                            ),
                        ],
                    ),
                    (
                        "Horn_Voice_I",
                        [
                            ide.Momento(
                                context="Horn_Voice_I",
                                prototype="abjad.Dynamic",
                                value="\\baca-sffz",
                            ),
                        ],
                    ),
                    (
                        "Horn_Voice_II",
                        [
                            ide.Momento(
                                context="Horn_Voice_II",
                                prototype="abjad.Dynamic",
                                value="\\baca-sffz",
                            ),
                        ],
                    ),
                    (
                        "Horn_Voice_III",
                        [
                            ide.Momento(
                                context="Horn_Voice_III",
                                edition=abjad.Tag("+PARTS"),
                                prototype="abjad.Dynamic",
                                value="\\baca-sffz",
                            ),
                        ],
                    ),
                    (
                        "Horn_Voice_IV",
                        [
                            ide.Momento(
                                context="Horn_Voice_IV",
                                edition=abjad.Tag("+PARTS"),
                                prototype="abjad.Dynamic",
                                value="\\baca-sffz",
                            ),
                        ],
                    ),
                    (
                        "Oboe_Staff_I",
                        [
                            ide.Momento(
                                context="Oboe_Voice_I",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Ob.",
                            ),
                            ide.Momento(
                                context="Oboe_Voice_I",
                                manifest="instruments",
                                value="Oboe",
                            ),
                            ide.Momento(
                                context="Oboe_Voice_I",
                                prototype="abjad.Clef",
                                value="treble",
                            ),
                        ],
                    ),
                    (
                        "Oboe_Voice_I",
                        [
                            ide.Momento(
                                context="Oboe_Voice_I",
                                prototype="abjad.Dynamic",
                                value="niente",
                            ),
                        ],
                    ),
                    (
                        "Percussion_Staff_I",
                        [
                            ide.Momento(
                                context="Percussion_Voice_I",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Perc. 1 (tri.)",
                            ),
                            ide.Momento(
                                context="Percussion_Voice_I",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="Percussion_Voice_I",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            ide.Momento(
                                context="Percussion_Voice_I",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="Percussion_Voice_I",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "Percussion_Staff_II",
                        [
                            ide.Momento(
                                context="Percussion_Voice_II",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Perc. 2 (cym.)",
                            ),
                            ide.Momento(
                                context="Percussion_Voice_II",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="Percussion_Voice_II",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            ide.Momento(
                                context="Percussion_Voice_II",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="Percussion_Voice_II",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "Percussion_Staff_III",
                        [
                            ide.Momento(
                                context="Percussion_Voice_III",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Perc. 3 (BD)",
                            ),
                            ide.Momento(
                                context="Percussion_Voice_III",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="Percussion_Voice_III",
                                manifest="instruments",
                                value="Vibraphone",
                            ),
                            ide.Momento(
                                context="Percussion_Voice_III",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="Percussion_Voice_III",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "Percussion_Staff_IV",
                        [
                            ide.Momento(
                                context="Percussion_Voice_IV",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Perc. 4 (slate)",
                            ),
                            ide.Momento(
                                context="Percussion_Voice_IV",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="Percussion_Voice_IV",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            ide.Momento(
                                context="Percussion_Voice_IV",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="Percussion_Voice_IV",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "Percussion_Voice_I",
                        [
                            ide.Momento(
                                context="Percussion_Voice_I",
                                prototype="abjad.Dynamic",
                                value="p",
                            ),
                        ],
                    ),
                    (
                        "Percussion_Voice_II",
                        [
                            ide.Momento(
                                context="Percussion_Voice_II",
                                prototype="abjad.Dynamic",
                                value="p",
                            ),
                        ],
                    ),
                    (
                        "Percussion_Voice_III",
                        [
                            ide.Momento(
                                context="Percussion_Voice_III",
                                prototype="abjad.Dynamic",
                                value="p",
                            ),
                        ],
                    ),
                    (
                        "Percussion_Voice_IV",
                        [
                            ide.Momento(
                                context="Percussion_Voice_IV",
                                prototype="abjad.Dynamic",
                                value="\\baca-effort-mf",
                            ),
                        ],
                    ),
                    (
                        "Piano_Piano_Staff",
                        [
                            ide.Momento(
                                context="Piano_Voice_I",
                                manifest="instruments",
                                value="Piano",
                            ),
                        ],
                    ),
                    (
                        "Piano_Staff_I",
                        [
                            ide.Momento(
                                context="Piano_Voice_I",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Pf.",
                            ),
                            ide.Momento(
                                context="Piano_Voice_I",
                                prototype="abjad.Clef",
                                value="treble",
                            ),
                        ],
                    ),
                    (
                        "Piano_Voice_I",
                        [
                            ide.Momento(
                                context="Piano_Voice_I",
                                prototype="abjad.Dynamic",
                                value="mf",
                            ),
                        ],
                    ),
                    (
                        "Score",
                        [
                            ide.Momento(
                                context="Global_Skips",
                                manifest="metronome_marks",
                                value="76",
                            ),
                            ide.Momento(
                                context="Global_Skips",
                                prototype="abjad.TimeSignature",
                                value="1/4",
                            ),
                        ],
                    ),
                    (
                        "Second_Violin_Staff_I",
                        [
                            ide.Momento(
                                context="Second_Violin_Voice_I",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vni. II (1-2)",
                            ),
                            ide.Momento(
                                context="Second_Violin_Voice_I",
                                manifest="instruments",
                                value="Violin",
                            ),
                            ide.Momento(
                                context="Second_Violin_Voice_II",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="Second_Violin_Voice_II",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="Second_Violin_Voice_II",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "Second_Violin_Staff_II",
                        [
                            ide.Momento(
                                context="Second_Violin_Voice_III",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vni. II (3-4)",
                            ),
                            ide.Momento(
                                context="Second_Violin_Voice_III",
                                manifest="instruments",
                                value="Violin",
                            ),
                            ide.Momento(
                                context="Second_Violin_Voice_IV",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="Second_Violin_Voice_IV",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="Second_Violin_Voice_IV",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "Second_Violin_Staff_III",
                        [
                            ide.Momento(
                                context="Second_Violin_Voice_V",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vni. II (5-6)",
                            ),
                            ide.Momento(
                                context="Second_Violin_Voice_V",
                                manifest="instruments",
                                value="Violin",
                            ),
                            ide.Momento(
                                context="Second_Violin_Voice_VI",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="Second_Violin_Voice_VI",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="Second_Violin_Voice_VI",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "Second_Violin_Staff_IV",
                        [
                            ide.Momento(
                                context="Second_Violin_Voice_VII",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vni. II (7-8)",
                            ),
                            ide.Momento(
                                context="Second_Violin_Voice_VII",
                                manifest="instruments",
                                value="Violin",
                            ),
                            ide.Momento(
                                context="Second_Violin_Voice_VIII",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="Second_Violin_Voice_VIII",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="Second_Violin_Voice_VIII",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "Second_Violin_Staff_IX",
                        [
                            ide.Momento(
                                context="Second_Violin_Voice_XVII",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vni. II (17-18)",
                            ),
                            ide.Momento(
                                context="Second_Violin_Voice_XVII",
                                manifest="instruments",
                                value="Violin",
                            ),
                            ide.Momento(
                                context="Second_Violin_Voice_XVIII",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="Second_Violin_Voice_XVIII",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="Second_Violin_Voice_XVIII",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "Second_Violin_Staff_V",
                        [
                            ide.Momento(
                                context="Second_Violin_Voice_IX",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vni. II (9-10)",
                            ),
                            ide.Momento(
                                context="Second_Violin_Voice_IX",
                                manifest="instruments",
                                value="Violin",
                            ),
                            ide.Momento(
                                context="Second_Violin_Voice_X",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="Second_Violin_Voice_X",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="Second_Violin_Voice_X",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "Second_Violin_Staff_VI",
                        [
                            ide.Momento(
                                context="Second_Violin_Voice_XI",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vni. II (11-12)",
                            ),
                            ide.Momento(
                                context="Second_Violin_Voice_XI",
                                manifest="instruments",
                                value="Violin",
                            ),
                            ide.Momento(
                                context="Second_Violin_Voice_XII",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="Second_Violin_Voice_XII",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="Second_Violin_Voice_XII",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "Second_Violin_Staff_VII",
                        [
                            ide.Momento(
                                context="Second_Violin_Voice_XIII",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vni. II (13-14)",
                            ),
                            ide.Momento(
                                context="Second_Violin_Voice_XIII",
                                manifest="instruments",
                                value="Violin",
                            ),
                            ide.Momento(
                                context="Second_Violin_Voice_XIV",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="Second_Violin_Voice_XIV",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="Second_Violin_Voice_XIV",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "Second_Violin_Staff_VIII",
                        [
                            ide.Momento(
                                context="Second_Violin_Voice_XV",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vni. II (15-16)",
                            ),
                            ide.Momento(
                                context="Second_Violin_Voice_XV",
                                manifest="instruments",
                                value="Violin",
                            ),
                            ide.Momento(
                                context="Second_Violin_Voice_XVI",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="Second_Violin_Voice_XVI",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="Second_Violin_Voice_XVI",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "Second_Violin_Voice_I",
                        [
                            ide.Momento(
                                context="Second_Violin_Voice_I",
                                prototype="abjad.Dynamic",
                                value="niente",
                            ),
                        ],
                    ),
                    (
                        "Second_Violin_Voice_II",
                        [
                            ide.Momento(
                                context="Second_Violin_Voice_II",
                                prototype="abjad.Dynamic",
                                value="niente",
                            ),
                        ],
                    ),
                    (
                        "Second_Violin_Voice_III",
                        [
                            ide.Momento(
                                context="Second_Violin_Voice_III",
                                prototype="abjad.Dynamic",
                                value="niente",
                            ),
                        ],
                    ),
                    (
                        "Second_Violin_Voice_IV",
                        [
                            ide.Momento(
                                context="Second_Violin_Voice_IV",
                                prototype="abjad.Dynamic",
                                value="niente",
                            ),
                        ],
                    ),
                    (
                        "Trombone_Staff_I",
                        [
                            ide.Momento(
                                context="Trombone_Voice_I",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Trb. (1+3)",
                            ),
                            ide.Momento(
                                context="Trombone_Voice_I",
                                manifest="instruments",
                                value="Trombone",
                            ),
                            ide.Momento(
                                context="Trombone_Voice_I",
                                prototype="abjad.Clef",
                                value="tenor",
                            ),
                        ],
                    ),
                    (
                        "Trombone_Staff_II",
                        [
                            ide.Momento(
                                context="Trombone_Voice_II",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Trb. (2+4)",
                            ),
                            ide.Momento(
                                context="Trombone_Voice_II",
                                manifest="instruments",
                                value="Trombone",
                            ),
                            ide.Momento(
                                context="Trombone_Voice_II",
                                prototype="abjad.Clef",
                                value="tenor",
                            ),
                        ],
                    ),
                    (
                        "Trombone_Voice_I",
                        [
                            ide.Momento(
                                context="Trombone_Voice_I",
                                prototype="abjad.Dynamic",
                                value="\\baca-sffz",
                            ),
                        ],
                    ),
                    (
                        "Trombone_Voice_II",
                        [
                            ide.Momento(
                                context="Trombone_Voice_II",
                                prototype="abjad.Dynamic",
                                value="\\baca-sffz",
                            ),
                        ],
                    ),
                    (
                        "Trombone_Voice_III",
                        [
                            ide.Momento(
                                context="Trombone_Voice_III",
                                edition=abjad.Tag("+PARTS"),
                                prototype="abjad.Dynamic",
                                value="\\baca-sffz",
                            ),
                        ],
                    ),
                    (
                        "Trombone_Voice_IV",
                        [
                            ide.Momento(
                                context="Trombone_Voice_IV",
                                edition=abjad.Tag("+PARTS"),
                                prototype="abjad.Dynamic",
                                value="\\baca-sffz",
                            ),
                        ],
                    ),
                    (
                        "Trumpet_Staff_I",
                        [
                            ide.Momento(
                                context="Trumpet_Voice_I",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Tp. (1+3)",
                            ),
                            ide.Momento(
                                context="Trumpet_Voice_I",
                                manifest="instruments",
                                value="Trumpet",
                            ),
                            ide.Momento(
                                context="Trumpet_Voice_I",
                                prototype="abjad.Clef",
                                value="treble",
                            ),
                        ],
                    ),
                    (
                        "Trumpet_Staff_II",
                        [
                            ide.Momento(
                                context="Trumpet_Voice_II",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Tp. (2+4)",
                            ),
                            ide.Momento(
                                context="Trumpet_Voice_II",
                                manifest="instruments",
                                value="Trumpet",
                            ),
                            ide.Momento(
                                context="Trumpet_Voice_II",
                                prototype="abjad.Clef",
                                value="treble",
                            ),
                        ],
                    ),
                    (
                        "Trumpet_Voice_I",
                        [
                            ide.Momento(
                                context="Trumpet_Voice_I",
                                prototype="abjad.Dynamic",
                                value="\\baca-sffz",
                            ),
                        ],
                    ),
                    (
                        "Trumpet_Voice_II",
                        [
                            ide.Momento(
                                context="Trumpet_Voice_II",
                                prototype="abjad.Dynamic",
                                value="\\baca-sffz",
                            ),
                        ],
                    ),
                    (
                        "Trumpet_Voice_III",
                        [
                            ide.Momento(
                                context="Trumpet_Voice_III",
                                edition=abjad.Tag("+PARTS"),
                                prototype="abjad.Dynamic",
                                value="\\baca-sffz",
                            ),
                        ],
                    ),
                    (
                        "Trumpet_Voice_IV",
                        [
                            ide.Momento(
                                context="Trumpet_Voice_IV",
                                edition=abjad.Tag("+PARTS"),
                                prototype="abjad.Dynamic",
                                value="\\baca-sffz",
                            ),
                        ],
                    ),
                    (
                        "Tuba_Staff_I",
                        [
                            ide.Momento(
                                context="Tuba_Voice_I",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Tub.",
                            ),
                            ide.Momento(
                                context="Tuba_Voice_I",
                                manifest="instruments",
                                value="Tuba",
                            ),
                            ide.Momento(
                                context="Tuba_Voice_I",
                                prototype="abjad.Clef",
                                value="bass",
                            ),
                        ],
                    ),
                    (
                        "Tuba_Voice_I",
                        [
                            ide.Momento(
                                context="Tuba_Voice_I",
                                prototype="abjad.Dynamic",
                                value="\\baca-sffz",
                            ),
                        ],
                    ),
                    (
                        "Viola_Staff_I",
                        [
                            ide.Momento(
                                context="Viola_Voice_I",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vle. (1-2)",
                            ),
                            ide.Momento(
                                context="Viola_Voice_I",
                                manifest="instruments",
                                value="Viola",
                            ),
                            ide.Momento(
                                context="Viola_Voice_II",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="Viola_Voice_II",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="Viola_Voice_II",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "Viola_Staff_II",
                        [
                            ide.Momento(
                                context="Viola_Voice_III",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vle. (3-4)",
                            ),
                            ide.Momento(
                                context="Viola_Voice_III",
                                manifest="instruments",
                                value="Viola",
                            ),
                            ide.Momento(
                                context="Viola_Voice_IV",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="Viola_Voice_IV",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="Viola_Voice_IV",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "Viola_Staff_III",
                        [
                            ide.Momento(
                                context="Viola_Voice_V",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vle. (5-6)",
                            ),
                            ide.Momento(
                                context="Viola_Voice_V",
                                manifest="instruments",
                                value="Viola",
                            ),
                            ide.Momento(
                                context="Viola_Voice_VI",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="Viola_Voice_VI",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="Viola_Voice_VI",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "Viola_Staff_IV",
                        [
                            ide.Momento(
                                context="Viola_Voice_VII",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vle. (7-8)",
                            ),
                            ide.Momento(
                                context="Viola_Voice_VII",
                                manifest="instruments",
                                value="Viola",
                            ),
                            ide.Momento(
                                context="Viola_Voice_VIII",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="Viola_Voice_VIII",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="Viola_Voice_VIII",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "Viola_Staff_IX",
                        [
                            ide.Momento(
                                context="Viola_Voice_XVII",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vle. (17-18)",
                            ),
                            ide.Momento(
                                context="Viola_Voice_XVII",
                                manifest="instruments",
                                value="Viola",
                            ),
                            ide.Momento(
                                context="Viola_Voice_XVIII",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="Viola_Voice_XVIII",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="Viola_Voice_XVIII",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "Viola_Staff_V",
                        [
                            ide.Momento(
                                context="Viola_Voice_IX",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vle. (9-10)",
                            ),
                            ide.Momento(
                                context="Viola_Voice_IX",
                                manifest="instruments",
                                value="Viola",
                            ),
                            ide.Momento(
                                context="Viola_Voice_X",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="Viola_Voice_X",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="Viola_Voice_X",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "Viola_Staff_VI",
                        [
                            ide.Momento(
                                context="Viola_Voice_XI",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vle. (11-12)",
                            ),
                            ide.Momento(
                                context="Viola_Voice_XI",
                                manifest="instruments",
                                value="Viola",
                            ),
                            ide.Momento(
                                context="Viola_Voice_XII",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="Viola_Voice_XII",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="Viola_Voice_XII",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "Viola_Staff_VII",
                        [
                            ide.Momento(
                                context="Viola_Voice_XIII",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vle. (13-14)",
                            ),
                            ide.Momento(
                                context="Viola_Voice_XIII",
                                manifest="instruments",
                                value="Viola",
                            ),
                            ide.Momento(
                                context="Viola_Voice_XIV",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="Viola_Voice_XIV",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="Viola_Voice_XIV",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "Viola_Staff_VIII",
                        [
                            ide.Momento(
                                context="Viola_Voice_XV",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vle. (15-16)",
                            ),
                            ide.Momento(
                                context="Viola_Voice_XV",
                                manifest="instruments",
                                value="Viola",
                            ),
                            ide.Momento(
                                context="Viola_Voice_XVI",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="Viola_Voice_XVI",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="Viola_Voice_XVI",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "Viola_Voice_I",
                        [
                            ide.Momento(
                                context="Viola_Voice_I",
                                prototype="abjad.Dynamic",
                                value="niente",
                            ),
                        ],
                    ),
                    (
                        "Viola_Voice_II",
                        [
                            ide.Momento(
                                context="Viola_Voice_II",
                                prototype="abjad.Dynamic",
                                value="niente",
                            ),
                        ],
                    ),
                    (
                        "Viola_Voice_III",
                        [
                            ide.Momento(
                                context="Viola_Voice_III",
                                prototype="abjad.Dynamic",
                                value="niente",
                            ),
                        ],
                    ),
                    (
                        "Viola_Voice_IV",
                        [
                            ide.Momento(
                                context="Viola_Voice_IV",
                                prototype="abjad.Dynamic",
                                value="niente",
                            ),
                        ],
                    ),
                ]
            ),
        ),
    ]
)
