import abjad
import baca

persist = abjad.OrderedDict(
    [
        (
            "alive_during_segment",
            [
                "Score",
                "Global_Context",
                "Global_Rests",
                "Global_Skips",
                "Music_Context",
                "Wind_Staff_Group",
                "OboeFamily_Square_Staff_Group",
                "Oboe_Staff_I",
                "Oboe_Voice_I",
                "Oboe_Rest_Voice_I",
                "English_Horn_Staff_I",
                "English_Horn_Voice_I",
                "English_Horn_Rest_Voice_I",
                "Bassoon_Staff_I",
                "Bassoon_Voice_I",
                "Bassoon_Rest_Voice_I",
                "Bassoon_Voice_II",
                "Bassoon_Rest_Voice_II",
                "String_Staff_Group",
                "FirstViolin_Square_Staff_Group",
                "First_Violin_Staff_I",
                "First_Violin_Voice_I",
                "First_Violin_Rest_Voice_I",
                "First_Violin_Voice_II",
                "First_Violin_Rest_Voice_II",
                "First_Violin_Staff_II",
                "First_Violin_Voice_III",
                "First_Violin_Rest_Voice_III",
                "First_Violin_Voice_IV",
                "First_Violin_Rest_Voice_IV",
                "First_Violin_Staff_III",
                "First_Violin_Voice_V",
                "First_Violin_Rest_Voice_V",
                "SecondViolin_Square_Staff_Group",
                "Second_Violin_Staff_I",
                "Second_Violin_Voice_I",
                "Second_Violin_Rest_Voice_I",
                "Second_Violin_Voice_II",
                "Second_Violin_Rest_Voice_II",
                "Second_Violin_Staff_II",
                "Second_Violin_Voice_III",
                "Second_Violin_Rest_Voice_III",
                "Second_Violin_Voice_IV",
                "Second_Violin_Rest_Voice_IV",
                "Viola_Square_Staff_Group",
                "Viola_Staff_I",
                "Viola_Voice_I",
                "Viola_Rest_Voice_I",
                "Viola_Voice_II",
                "Viola_Rest_Voice_II",
                "Viola_Staff_II",
                "Viola_Voice_III",
                "Viola_Rest_Voice_III",
                "Viola_Voice_IV",
                "Viola_Rest_Voice_IV",
                "Cello_Staff_I",
                "Cello_Voice_I",
                "Cello_Rest_Voice_I",
                "Cello_Voice_II",
                "Cello_Rest_Voice_II",
                "Contrabass_Staff_II",
                "Contrabass_Voice_III",
                "Contrabass_Rest_Voice_III",
            ],
        ),
        (
            "container_to_part_assignment",
            abjad.OrderedDict(
                [
                    (
                        "p_Bassoon_Voice_II_a",
                        (
                            baca.PartAssignment("Bassoon", 2),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((23, 2)),
                            ),
                        ),
                    ),
                    (
                        "p_Bassoon_Voice_I_a",
                        (
                            baca.PartAssignment("Bassoon", 1),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((23, 2)),
                            ),
                        ),
                    ),
                    (
                        "p_Cello_Voice_II_a",
                        (
                            baca.PartAssignment("Cello", (9, 14)),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((23, 2)),
                            ),
                        ),
                    ),
                    (
                        "p_Cello_Voice_I_a",
                        (
                            baca.PartAssignment("Cello", (1, 8)),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((23, 2)),
                            ),
                        ),
                    ),
                    (
                        "p_Contrabass_Voice_III_a",
                        (
                            baca.PartAssignment("Contrabass"),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((23, 2)),
                            ),
                        ),
                    ),
                    (
                        "p_English_Horn_Voice_I_a",
                        (
                            baca.PartAssignment("English_Horn"),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((23, 2)),
                            ),
                        ),
                    ),
                    (
                        "p_First_Violin_Voice_III_a",
                        (
                            baca.PartAssignment("First_Violin", (9, 12)),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((23, 2)),
                            ),
                        ),
                    ),
                    (
                        "p_First_Violin_Voice_II_a",
                        (
                            baca.PartAssignment("First_Violin", (5, 8)),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((23, 2)),
                            ),
                        ),
                    ),
                    (
                        "p_First_Violin_Voice_IV_a",
                        (
                            baca.PartAssignment("First_Violin", (13, 17)),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((23, 2)),
                            ),
                        ),
                    ),
                    (
                        "p_First_Violin_Voice_I_a",
                        (
                            baca.PartAssignment("First_Violin", (1, 4)),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((23, 2)),
                            ),
                        ),
                    ),
                    (
                        "p_First_Violin_Voice_V_a",
                        (
                            baca.PartAssignment("First_Violin", 18),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((23, 2)),
                            ),
                        ),
                    ),
                    (
                        "p_Oboe_Voice_I_a",
                        (
                            baca.PartAssignment("Oboe"),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((23, 2)),
                            ),
                        ),
                    ),
                    (
                        "p_Second_Violin_Voice_III_a",
                        (
                            baca.PartAssignment("Second_Violin", (9, 12)),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((23, 2)),
                            ),
                        ),
                    ),
                    (
                        "p_Second_Violin_Voice_II_a",
                        (
                            baca.PartAssignment("Second_Violin", (5, 8)),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((23, 2)),
                            ),
                        ),
                    ),
                    (
                        "p_Second_Violin_Voice_IV_a",
                        (
                            baca.PartAssignment("Second_Violin", (13, 18)),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((23, 2)),
                            ),
                        ),
                    ),
                    (
                        "p_Second_Violin_Voice_I_a",
                        (
                            baca.PartAssignment("Second_Violin", (1, 4)),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((23, 2)),
                            ),
                        ),
                    ),
                    (
                        "p_Viola_Voice_III_a",
                        (
                            baca.PartAssignment("Viola", (9, 12)),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((23, 2)),
                            ),
                        ),
                    ),
                    (
                        "p_Viola_Voice_II_a",
                        (
                            baca.PartAssignment("Viola", (5, 8)),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((23, 2)),
                            ),
                        ),
                    ),
                    (
                        "p_Viola_Voice_IV_a",
                        (
                            baca.PartAssignment("Viola", (13, 18)),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((23, 2)),
                            ),
                        ),
                    ),
                    (
                        "p_Viola_Voice_I_a",
                        (
                            baca.PartAssignment("Viola", (1, 4)),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((23, 2)),
                            ),
                        ),
                    ),
                ]
            ),
        ),
        (
            "persistent_indicators",
            abjad.OrderedDict(
                [
                    (
                        "Bass_Clarinet_Staff_I",
                        [
                            baca.Momento(
                                context="Bass_Clarinet_Voice_I",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="B. cl.",
                            ),
                            baca.Momento(
                                context="Bass_Clarinet_Voice_I",
                                manifest="instruments",
                                value="BassClarinet",
                            ),
                            baca.Momento(
                                context="Bass_Clarinet_Voice_I",
                                prototype="abjad.Clef",
                                value="treble",
                            ),
                        ],
                    ),
                    (
                        "Bass_Clarinet_Voice_I",
                        [
                            baca.Momento(
                                context="Bass_Clarinet_Voice_I",
                                prototype="abjad.Dynamic",
                                value="p",
                            ),
                        ],
                    ),
                    (
                        "Bassoon_Staff_I",
                        [
                            baca.Momento(
                                context="Bassoon_Voice_I",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Bsn.",
                            ),
                            baca.Momento(
                                context="Bassoon_Voice_I",
                                manifest="instruments",
                                value="Bassoon",
                            ),
                            baca.Momento(
                                context="Bassoon_Voice_I",
                                prototype="abjad.Clef",
                                value="bass",
                            ),
                        ],
                    ),
                    (
                        "Bassoon_Voice_I",
                        [
                            baca.Momento(
                                context="Bassoon_Voice_I",
                                edition=abjad.Tag("+PARTS"),
                                prototype="abjad.Dynamic",
                                value="niente",
                            ),
                        ],
                    ),
                    (
                        "Bassoon_Voice_II",
                        [
                            baca.Momento(
                                context="Bassoon_Voice_II",
                                prototype="abjad.Dynamic",
                                value="niente",
                            ),
                        ],
                    ),
                    (
                        "Cello_Staff_I",
                        [
                            baca.Momento(
                                context="Cello_Voice_I",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vc. (1-8) (9-14)",
                            ),
                            baca.Momento(
                                context="Cello_Voice_I",
                                manifest="instruments",
                                value="Cello",
                            ),
                            baca.Momento(
                                context="Cello_Voice_I",
                                prototype="abjad.Clef",
                                value="bass",
                            ),
                        ],
                    ),
                    (
                        "Cello_Voice_I",
                        [
                            baca.Momento(
                                context="Cello_Voice_I",
                                prototype="abjad.Dynamic",
                                value="pp",
                            ),
                        ],
                    ),
                    (
                        "Cello_Voice_II",
                        [
                            baca.Momento(
                                context="Cello_Voice_II",
                                prototype="abjad.Dynamic",
                                value="pp",
                            ),
                        ],
                    ),
                    (
                        "Clarinet_Staff_I",
                        [
                            baca.Momento(
                                context="Clarinet_Voice_I",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Cl. 1",
                            ),
                            baca.Momento(
                                context="Clarinet_Voice_I",
                                manifest="instruments",
                                value="Clarinet",
                            ),
                            baca.Momento(
                                context="Clarinet_Voice_I",
                                prototype="abjad.Clef",
                                value="treble",
                            ),
                        ],
                    ),
                    (
                        "Clarinet_Voice_I",
                        [
                            baca.Momento(
                                context="Clarinet_Voice_I",
                                prototype="abjad.Dynamic",
                                value="ff",
                            ),
                        ],
                    ),
                    (
                        "Contrabass_Staff_I",
                        [
                            baca.Momento(
                                context="Contrabass_Voice_I",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Cb. 1",
                            ),
                            baca.Momento(
                                context="Contrabass_Voice_I",
                                manifest="instruments",
                                value="Contrabass",
                            ),
                            baca.Momento(
                                context="Contrabass_Voice_I",
                                prototype="abjad.Clef",
                                value="treble",
                            ),
                        ],
                    ),
                    (
                        "Contrabass_Staff_II",
                        [
                            baca.Momento(
                                context="Contrabass_Voice_III",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Cb.",
                            ),
                            baca.Momento(
                                context="Contrabass_Voice_III",
                                manifest="instruments",
                                value="Contrabass",
                            ),
                            baca.Momento(
                                context="Contrabass_Voice_III",
                                prototype="abjad.Clef",
                                value="bass",
                            ),
                        ],
                    ),
                    (
                        "Contrabass_Voice_I",
                        [
                            baca.Momento(
                                context="Contrabass_Voice_I",
                                prototype="abjad.Dynamic",
                                value="mf",
                            ),
                        ],
                    ),
                    (
                        "Contrabass_Voice_III",
                        [
                            baca.Momento(
                                context="Contrabass_Voice_III",
                                prototype="abjad.Dynamic",
                                value="pp",
                            ),
                        ],
                    ),
                    (
                        "English_Horn_Staff_I",
                        [
                            baca.Momento(
                                context="English_Horn_Voice_I",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Eng. hn.",
                            ),
                            baca.Momento(
                                context="English_Horn_Voice_I",
                                manifest="instruments",
                                value="EnglishHorn",
                            ),
                            baca.Momento(
                                context="English_Horn_Voice_I",
                                prototype="abjad.Clef",
                                value="treble",
                            ),
                        ],
                    ),
                    (
                        "English_Horn_Voice_I",
                        [
                            baca.Momento(
                                context="English_Horn_Voice_I",
                                prototype="abjad.Dynamic",
                                value="niente",
                            ),
                        ],
                    ),
                    (
                        "First_Violin_Staff_I",
                        [
                            baca.Momento(
                                context="First_Violin_Voice_I",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vni. I (1-4) (5-8)",
                            ),
                            baca.Momento(
                                context="First_Violin_Voice_I",
                                manifest="instruments",
                                value="Violin",
                            ),
                            baca.Momento(
                                context="First_Violin_Voice_I",
                                prototype="abjad.Clef",
                                value="treble",
                            ),
                        ],
                    ),
                    (
                        "First_Violin_Staff_II",
                        [
                            baca.Momento(
                                context="First_Violin_Voice_III",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vni. I (9-12) (13-17)",
                            ),
                            baca.Momento(
                                context="First_Violin_Voice_III",
                                manifest="instruments",
                                value="Violin",
                            ),
                            baca.Momento(
                                context="First_Violin_Voice_III",
                                prototype="abjad.Clef",
                                value="treble",
                            ),
                        ],
                    ),
                    (
                        "First_Violin_Staff_III",
                        [
                            baca.Momento(
                                context="First_Violin_Voice_V",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vni. I 18",
                            ),
                            baca.Momento(
                                context="First_Violin_Voice_V",
                                manifest="instruments",
                                value="Violin",
                            ),
                            baca.Momento(
                                context="First_Violin_Voice_V",
                                prototype="abjad.Clef",
                                value="treble",
                            ),
                        ],
                    ),
                    (
                        "First_Violin_Voice_I",
                        [
                            baca.Momento(
                                context="First_Violin_Voice_I",
                                prototype="abjad.Dynamic",
                                value="pp",
                            ),
                        ],
                    ),
                    (
                        "First_Violin_Voice_II",
                        [
                            baca.Momento(
                                context="First_Violin_Voice_II",
                                prototype="abjad.Dynamic",
                                value="pp",
                            ),
                        ],
                    ),
                    (
                        "First_Violin_Voice_III",
                        [
                            baca.Momento(
                                context="First_Violin_Voice_III",
                                prototype="abjad.Dynamic",
                                value="pp",
                            ),
                        ],
                    ),
                    (
                        "First_Violin_Voice_IV",
                        [
                            baca.Momento(
                                context="First_Violin_Voice_IV",
                                prototype="abjad.Dynamic",
                                value="pp",
                            ),
                        ],
                    ),
                    (
                        "First_Violin_Voice_V",
                        [
                            baca.Momento(
                                context="First_Violin_Voice_V",
                                prototype="abjad.Dynamic",
                                value="f",
                            ),
                        ],
                    ),
                    (
                        "Flute_Staff_I",
                        [
                            baca.Momento(
                                context="Flute_Voice_I",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Fl. (1+3)",
                            ),
                            baca.Momento(
                                context="Flute_Voice_I",
                                manifest="instruments",
                                value="Flute",
                            ),
                            baca.Momento(
                                context="Flute_Voice_I",
                                prototype="abjad.Clef",
                                value="treble",
                            ),
                        ],
                    ),
                    (
                        "Flute_Staff_II",
                        [
                            baca.Momento(
                                context="Flute_Voice_II",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Fl. (2+4)",
                            ),
                            baca.Momento(
                                context="Flute_Voice_II",
                                manifest="instruments",
                                value="Flute",
                            ),
                            baca.Momento(
                                context="Flute_Voice_II",
                                prototype="abjad.Clef",
                                value="treble",
                            ),
                        ],
                    ),
                    (
                        "Flute_Voice_I",
                        [
                            baca.Momento(
                                context="Flute_Voice_I",
                                edition=abjad.Tag("+PARTS"),
                                prototype="abjad.Dynamic",
                                value="ff",
                            ),
                        ],
                    ),
                    (
                        "Flute_Voice_II",
                        [
                            baca.Momento(
                                context="Flute_Voice_II",
                                edition=abjad.Tag("+PARTS"),
                                prototype="abjad.Dynamic",
                                value="ff",
                            ),
                        ],
                    ),
                    (
                        "Flute_Voice_III",
                        [
                            baca.Momento(
                                context="Flute_Voice_III",
                                prototype="abjad.Dynamic",
                                value="ff",
                            ),
                        ],
                    ),
                    (
                        "Flute_Voice_IV",
                        [
                            baca.Momento(
                                context="Flute_Voice_IV",
                                prototype="abjad.Dynamic",
                                value="ff",
                            ),
                        ],
                    ),
                    (
                        "Harp_Piano_Staff",
                        [
                            baca.Momento(
                                context="Harp_Voice_I",
                                manifest="instruments",
                                value="Harp",
                            ),
                        ],
                    ),
                    (
                        "Harp_Staff_I",
                        [
                            baca.Momento(
                                context="Harp_Voice_I",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Hp.",
                            ),
                            baca.Momento(
                                context="Harp_Voice_I",
                                prototype="abjad.Clef",
                                value="treble",
                            ),
                        ],
                    ),
                    (
                        "Harp_Voice_I",
                        [
                            baca.Momento(
                                context="Harp_Voice_I",
                                prototype="abjad.Dynamic",
                                value="mf",
                            ),
                        ],
                    ),
                    (
                        "Horn_Staff_I",
                        [
                            baca.Momento(
                                context="Horn_Voice_I",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Hn. (1+3)",
                            ),
                            baca.Momento(
                                context="Horn_Voice_I",
                                manifest="instruments",
                                value="Horn",
                            ),
                            baca.Momento(
                                context="Horn_Voice_I",
                                prototype="abjad.Clef",
                                value="bass",
                            ),
                        ],
                    ),
                    (
                        "Horn_Staff_II",
                        [
                            baca.Momento(
                                context="Horn_Voice_II",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Hn. (2+4)",
                            ),
                            baca.Momento(
                                context="Horn_Voice_II",
                                manifest="instruments",
                                value="Horn",
                            ),
                            baca.Momento(
                                context="Horn_Voice_II",
                                prototype="abjad.Clef",
                                value="bass",
                            ),
                        ],
                    ),
                    (
                        "Horn_Voice_I",
                        [
                            baca.Momento(
                                context="Horn_Voice_I",
                                edition=abjad.Tag("+PARTS"),
                                prototype="abjad.Dynamic",
                                value="sfz",
                            ),
                        ],
                    ),
                    (
                        "Horn_Voice_II",
                        [
                            baca.Momento(
                                context="Horn_Voice_II",
                                edition=abjad.Tag("+PARTS"),
                                prototype="abjad.Dynamic",
                                value="sfz",
                            ),
                        ],
                    ),
                    (
                        "Horn_Voice_III",
                        [
                            baca.Momento(
                                context="Horn_Voice_III",
                                prototype="abjad.Dynamic",
                                value="sfz",
                            ),
                        ],
                    ),
                    (
                        "Horn_Voice_IV",
                        [
                            baca.Momento(
                                context="Horn_Voice_IV",
                                prototype="abjad.Dynamic",
                                value="sfz",
                            ),
                        ],
                    ),
                    (
                        "Oboe_Staff_I",
                        [
                            baca.Momento(
                                context="Oboe_Voice_I",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Ob.",
                            ),
                            baca.Momento(
                                context="Oboe_Voice_I",
                                manifest="instruments",
                                value="Oboe",
                            ),
                            baca.Momento(
                                context="Oboe_Voice_I",
                                prototype="abjad.Clef",
                                value="treble",
                            ),
                        ],
                    ),
                    (
                        "Oboe_Voice_I",
                        [
                            baca.Momento(
                                context="Oboe_Voice_I",
                                prototype="abjad.Dynamic",
                                value="niente",
                            ),
                        ],
                    ),
                    (
                        "Percussion_Staff_I",
                        [
                            baca.Momento(
                                context="Percussion_Voice_I",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Perc. 1 (tri.)",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_I",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            baca.Momento(
                                context="Percussion_Voice_I",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_I",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_I",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "Percussion_Staff_II",
                        [
                            baca.Momento(
                                context="Percussion_Voice_II",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Perc. 2 (cym.)",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_II",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            baca.Momento(
                                context="Percussion_Voice_II",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_II",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_II",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "Percussion_Staff_III",
                        [
                            baca.Momento(
                                context="Percussion_Voice_III",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Perc. 3 (vib.)",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_III",
                                manifest="instruments",
                                value="Vibraphone",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_III",
                                prototype="abjad.Clef",
                                value="treble",
                            ),
                        ],
                    ),
                    (
                        "Percussion_Staff_IV",
                        [
                            baca.Momento(
                                context="Percussion_Voice_IV",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Perc.",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_IV",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            baca.Momento(
                                context="Percussion_Voice_IV",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_IV",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_IV",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "Percussion_Voice_I",
                        [
                            baca.Momento(
                                context="Percussion_Voice_I",
                                prototype="abjad.Dynamic",
                                value="mp",
                            ),
                        ],
                    ),
                    (
                        "Percussion_Voice_II",
                        [
                            baca.Momento(
                                context="Percussion_Voice_II",
                                prototype="abjad.Dynamic",
                                value="mp",
                            ),
                        ],
                    ),
                    (
                        "Percussion_Voice_III",
                        [
                            baca.Momento(
                                context="Percussion_Voice_III",
                                prototype="abjad.Dynamic",
                                value="mp",
                            ),
                        ],
                    ),
                    (
                        "Piano_Piano_Staff",
                        [
                            baca.Momento(
                                context="Piano_Voice_I",
                                manifest="instruments",
                                value="Piano",
                            ),
                        ],
                    ),
                    (
                        "Piano_Staff_I",
                        [
                            baca.Momento(
                                context="Piano_Voice_I",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Pf.",
                            ),
                            baca.Momento(
                                context="Piano_Voice_I",
                                prototype="abjad.Clef",
                                value="treble",
                            ),
                        ],
                    ),
                    (
                        "Piano_Voice_I",
                        [
                            baca.Momento(
                                context="Piano_Voice_I",
                                prototype="abjad.Dynamic",
                                value="mf",
                            ),
                        ],
                    ),
                    (
                        "Score",
                        [
                            baca.Momento(
                                context="Global_Skips",
                                manifest="metronome_marks",
                                value="114",
                            ),
                            baca.Momento(
                                context="Global_Skips",
                                prototype="abjad.TimeSignature",
                                value="2/4",
                            ),
                        ],
                    ),
                    (
                        "Second_Violin_Staff_I",
                        [
                            baca.Momento(
                                context="Second_Violin_Voice_I",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vni. II (1-4) (5-8)",
                            ),
                            baca.Momento(
                                context="Second_Violin_Voice_I",
                                manifest="instruments",
                                value="Violin",
                            ),
                            baca.Momento(
                                context="Second_Violin_Voice_I",
                                prototype="abjad.Clef",
                                value="treble",
                            ),
                        ],
                    ),
                    (
                        "Second_Violin_Staff_II",
                        [
                            baca.Momento(
                                context="Second_Violin_Voice_III",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vni. II (9-12) (13-18)",
                            ),
                            baca.Momento(
                                context="Second_Violin_Voice_III",
                                manifest="instruments",
                                value="Violin",
                            ),
                            baca.Momento(
                                context="Second_Violin_Voice_III",
                                prototype="abjad.Clef",
                                value="treble",
                            ),
                        ],
                    ),
                    (
                        "Second_Violin_Voice_I",
                        [
                            baca.Momento(
                                context="Second_Violin_Voice_I",
                                prototype="abjad.Dynamic",
                                value="pp",
                            ),
                        ],
                    ),
                    (
                        "Second_Violin_Voice_II",
                        [
                            baca.Momento(
                                context="Second_Violin_Voice_II",
                                prototype="abjad.Dynamic",
                                value="pp",
                            ),
                        ],
                    ),
                    (
                        "Second_Violin_Voice_III",
                        [
                            baca.Momento(
                                context="Second_Violin_Voice_III",
                                prototype="abjad.Dynamic",
                                value="pp",
                            ),
                        ],
                    ),
                    (
                        "Second_Violin_Voice_IV",
                        [
                            baca.Momento(
                                context="Second_Violin_Voice_IV",
                                prototype="abjad.Dynamic",
                                value="pp",
                            ),
                        ],
                    ),
                    (
                        "Trombone_Staff_I",
                        [
                            baca.Momento(
                                context="Trombone_Voice_I",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Trb. (1+3)",
                            ),
                            baca.Momento(
                                context="Trombone_Voice_I",
                                manifest="instruments",
                                value="Trombone",
                            ),
                            baca.Momento(
                                context="Trombone_Voice_I",
                                prototype="abjad.Clef",
                                value="tenor",
                            ),
                        ],
                    ),
                    (
                        "Trombone_Staff_II",
                        [
                            baca.Momento(
                                context="Trombone_Voice_II",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Trb. (2+4)",
                            ),
                            baca.Momento(
                                context="Trombone_Voice_II",
                                manifest="instruments",
                                value="Trombone",
                            ),
                            baca.Momento(
                                context="Trombone_Voice_II",
                                prototype="abjad.Clef",
                                value="tenor",
                            ),
                        ],
                    ),
                    (
                        "Trombone_Voice_I",
                        [
                            baca.Momento(
                                context="Trombone_Voice_I",
                                edition=abjad.Tag("+PARTS"),
                                prototype="abjad.Dynamic",
                                value="sfz",
                            ),
                        ],
                    ),
                    (
                        "Trombone_Voice_II",
                        [
                            baca.Momento(
                                context="Trombone_Voice_II",
                                edition=abjad.Tag("+PARTS"),
                                prototype="abjad.Dynamic",
                                value="sfz",
                            ),
                        ],
                    ),
                    (
                        "Trombone_Voice_III",
                        [
                            baca.Momento(
                                context="Trombone_Voice_III",
                                prototype="abjad.Dynamic",
                                value="sfz",
                            ),
                        ],
                    ),
                    (
                        "Trombone_Voice_IV",
                        [
                            baca.Momento(
                                context="Trombone_Voice_IV",
                                prototype="abjad.Dynamic",
                                value="sfz",
                            ),
                        ],
                    ),
                    (
                        "Trumpet_Staff_I",
                        [
                            baca.Momento(
                                context="Trumpet_Voice_I",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Tp. (1+3)",
                            ),
                            baca.Momento(
                                context="Trumpet_Voice_I",
                                manifest="instruments",
                                value="Trumpet",
                            ),
                            baca.Momento(
                                context="Trumpet_Voice_I",
                                prototype="abjad.Clef",
                                value="treble",
                            ),
                        ],
                    ),
                    (
                        "Trumpet_Staff_II",
                        [
                            baca.Momento(
                                context="Trumpet_Voice_II",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Tp. (2+4)",
                            ),
                            baca.Momento(
                                context="Trumpet_Voice_II",
                                manifest="instruments",
                                value="Trumpet",
                            ),
                            baca.Momento(
                                context="Trumpet_Voice_II",
                                prototype="abjad.Clef",
                                value="treble",
                            ),
                        ],
                    ),
                    (
                        "Trumpet_Voice_I",
                        [
                            baca.Momento(
                                context="Trumpet_Voice_I",
                                edition=abjad.Tag("+PARTS"),
                                prototype="abjad.Dynamic",
                                value="sfz",
                            ),
                        ],
                    ),
                    (
                        "Trumpet_Voice_II",
                        [
                            baca.Momento(
                                context="Trumpet_Voice_II",
                                edition=abjad.Tag("+PARTS"),
                                prototype="abjad.Dynamic",
                                value="sfz",
                            ),
                        ],
                    ),
                    (
                        "Trumpet_Voice_III",
                        [
                            baca.Momento(
                                context="Trumpet_Voice_III",
                                prototype="abjad.Dynamic",
                                value="sfz",
                            ),
                        ],
                    ),
                    (
                        "Trumpet_Voice_IV",
                        [
                            baca.Momento(
                                context="Trumpet_Voice_IV",
                                prototype="abjad.Dynamic",
                                value="sfz",
                            ),
                        ],
                    ),
                    (
                        "Tuba_Staff_I",
                        [
                            baca.Momento(
                                context="Tuba_Voice_I",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Tub.",
                            ),
                            baca.Momento(
                                context="Tuba_Voice_I",
                                manifest="instruments",
                                value="Tuba",
                            ),
                            baca.Momento(
                                context="Tuba_Voice_I",
                                prototype="abjad.Clef",
                                value="bass",
                            ),
                        ],
                    ),
                    (
                        "Tuba_Voice_I",
                        [
                            baca.Momento(
                                context="Tuba_Voice_I",
                                prototype="abjad.Dynamic",
                                value="\\baca-sffz",
                            ),
                        ],
                    ),
                    (
                        "Viola_Staff_I",
                        [
                            baca.Momento(
                                context="Viola_Voice_I",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vle. (1-4) (5-8)",
                            ),
                            baca.Momento(
                                context="Viola_Voice_I",
                                manifest="instruments",
                                value="Viola",
                            ),
                            baca.Momento(
                                context="Viola_Voice_I",
                                prototype="abjad.Clef",
                                value="alto",
                            ),
                        ],
                    ),
                    (
                        "Viola_Staff_II",
                        [
                            baca.Momento(
                                context="Viola_Voice_III",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vle. (9-12) (13-18)",
                            ),
                            baca.Momento(
                                context="Viola_Voice_III",
                                manifest="instruments",
                                value="Viola",
                            ),
                            baca.Momento(
                                context="Viola_Voice_III",
                                prototype="abjad.Clef",
                                value="alto",
                            ),
                        ],
                    ),
                    (
                        "Viola_Voice_I",
                        [
                            baca.Momento(
                                context="Viola_Voice_I",
                                prototype="abjad.Dynamic",
                                value="pp",
                            ),
                        ],
                    ),
                    (
                        "Viola_Voice_II",
                        [
                            baca.Momento(
                                context="Viola_Voice_II",
                                prototype="abjad.Dynamic",
                                value="pp",
                            ),
                        ],
                    ),
                    (
                        "Viola_Voice_III",
                        [
                            baca.Momento(
                                context="Viola_Voice_III",
                                prototype="abjad.Dynamic",
                                value="pp",
                            ),
                        ],
                    ),
                    (
                        "Viola_Voice_IV",
                        [
                            baca.Momento(
                                context="Viola_Voice_IV",
                                prototype="abjad.Dynamic",
                                value="pp",
                            ),
                        ],
                    ),
                ]
            ),
        ),
    ]
)
