import abjad


metadata = abjad.OrderedDict(
    [
        (
            'alive_during_segment',
            [
                'Score',
                'Global_Context',
                'Global_Rests',
                'Global_Skips',
                'Music_Context',
                'Brass_Staff_Group',
                'Horn_Square_Staff_Group',
                'Horn_Staff_I',
                'Horn_Voice_I',
                'Horn_Voice_III',
                'Horn_Staff_II',
                'Horn_Voice_II',
                'Horn_Voice_IV',
                'Trumpet_Square_Staff_Group',
                'Trumpet_Staff_I',
                'Trumpet_Voice_I',
                'Trumpet_Voice_III',
                'Trumpet_Staff_II',
                'Trumpet_Voice_II',
                'Trumpet_Voice_IV',
                'Trombone_Square_Staff_Group',
                'Trombone_Staff_I',
                'Trombone_Voice_I',
                'Trombone_Voice_III',
                'Trombone_Staff_II',
                'Trombone_Voice_II',
                'Trombone_Voice_IV',
                'Tuba_Staff_I',
                'Tuba_Voice_I',
                'Piano_Piano_Staff',
                'Piano_Staff_I',
                'Piano_Voice_I',
                'Percussion_Staff_Group',
                'Percussion_Staff_I',
                'Percussion_Voice_I',
                'Percussion_Staff_II',
                'Percussion_Voice_II',
                'Percussion_Staff_III',
                'Percussion_Voice_III',
                'Percussion_Staff_IV',
                'Percussion_Voice_IV',
                'String_Staff_Group',
                'FirstViolin_Square_Staff_Group',
                'First_Violin_Staff_I',
                'First_Violin_Voice_I',
                'First_Violin_Voice_II',
                'First_Violin_Staff_II',
                'First_Violin_Voice_III',
                'First_Violin_Voice_IV',
                'First_Violin_Staff_III',
                'First_Violin_Voice_V',
                'First_Violin_Voice_VI',
                'First_Violin_Staff_IV',
                'First_Violin_Voice_VII',
                'First_Violin_Voice_VIII',
                'First_Violin_Staff_V',
                'First_Violin_Voice_IX',
                'First_Violin_Voice_X',
                'First_Violin_Staff_VI',
                'First_Violin_Voice_XI',
                'First_Violin_Voice_XII',
                'First_Violin_Staff_VII',
                'First_Violin_Voice_XIII',
                'First_Violin_Voice_XIV',
                'First_Violin_Staff_VIII',
                'First_Violin_Voice_XV',
                'First_Violin_Voice_XVI',
                'First_Violin_Staff_IX',
                'First_Violin_Voice_XVII',
                'First_Violin_Voice_XVIII',
                'SecondViolin_Square_Staff_Group',
                'Second_Violin_Staff_I',
                'Second_Violin_Voice_I',
                'Second_Violin_Voice_II',
                'Second_Violin_Staff_II',
                'Second_Violin_Voice_III',
                'Second_Violin_Voice_IV',
                'Second_Violin_Staff_III',
                'Second_Violin_Voice_V',
                'Second_Violin_Voice_VI',
                'Second_Violin_Staff_IV',
                'Second_Violin_Voice_VII',
                'Second_Violin_Voice_VIII',
                'Second_Violin_Staff_V',
                'Second_Violin_Voice_IX',
                'Second_Violin_Voice_X',
                'Second_Violin_Staff_VI',
                'Second_Violin_Voice_XI',
                'Second_Violin_Voice_XII',
                'Second_Violin_Staff_VII',
                'Second_Violin_Voice_XIII',
                'Second_Violin_Voice_XIV',
                'Second_Violin_Staff_VIII',
                'Second_Violin_Voice_XV',
                'Second_Violin_Voice_XVI',
                'Second_Violin_Staff_IX',
                'Second_Violin_Voice_XVII',
                'Second_Violin_Voice_XVIII',
                'Viola_Square_Staff_Group',
                'Viola_Staff_I',
                'Viola_Voice_I',
                'Viola_Voice_II',
                'Viola_Staff_II',
                'Viola_Voice_III',
                'Viola_Voice_IV',
                'Viola_Staff_III',
                'Viola_Voice_V',
                'Viola_Voice_VI',
                'Viola_Staff_IV',
                'Viola_Voice_VII',
                'Viola_Voice_VIII',
                'Viola_Staff_V',
                'Viola_Voice_IX',
                'Viola_Voice_X',
                'Viola_Staff_VI',
                'Viola_Voice_XI',
                'Viola_Voice_XII',
                'Viola_Staff_VII',
                'Viola_Voice_XIII',
                'Viola_Voice_XIV',
                'Viola_Staff_VIII',
                'Viola_Voice_XV',
                'Viola_Voice_XVI',
                'Viola_Staff_IX',
                'Viola_Voice_XVII',
                'Viola_Voice_XVIII',
                'Cello_Square_Staff_Group',
                'Cello_Staff_I',
                'Cello_Voice_I',
                'Cello_Voice_II',
                'Cello_Staff_II',
                'Cello_Voice_III',
                'Cello_Voice_IV',
                'Cello_Staff_III',
                'Cello_Voice_V',
                'Cello_Voice_VI',
                'Cello_Staff_IV',
                'Cello_Voice_VII',
                'Cello_Voice_VIII',
                'Cello_Staff_V',
                'Cello_Voice_IX',
                'Cello_Voice_X',
                'Cello_Staff_VI',
                'Cello_Voice_XI',
                'Cello_Voice_XII',
                'Cello_Staff_VII',
                'Cello_Voice_XIII',
                'Cello_Voice_XIV',
                'Contrabass_Square_Staff_Group',
                'Contrabass_Staff_I',
                'Contrabass_Voice_I',
                'Contrabass_Voice_II',
                'Contrabass_Staff_II',
                'Contrabass_Voice_III',
                'Contrabass_Voice_IV',
                'Contrabass_Staff_III',
                'Contrabass_Voice_V',
                'Contrabass_Voice_VI',
                ],
            ),
        (
            'bol_measure_numbers',
            [131],
            ),
        ('duration', "0'07''"),
        ('final_measure_number', 133),
        (
            'first_appearance_margin_markup',
            abjad.OrderedDict(
                [
                    ('Cello_Staff_II', 'Vc. (3-4)'),
                    ('Cello_Staff_III', 'Vc. (5-6)'),
                    ('Cello_Staff_IV', 'Vc. (7-8)'),
                    ('Cello_Staff_V', 'Vc. (9-10)'),
                    ('Cello_Staff_VI', 'Vc. (11-12)'),
                    ('Cello_Staff_VII', 'Vc. (13-14)'),
                    ('Contrabass_Staff_III', 'Cb. (5-6)'),
                    ('First_Violin_Staff_IV', 'Vni. I (7-8)'),
                    ('First_Violin_Staff_IX', 'Vni. I (17-18)'),
                    ('First_Violin_Staff_V', 'Vni. I (9-10)'),
                    ('First_Violin_Staff_VI', 'Vni. I (11-12)'),
                    ('First_Violin_Staff_VII', 'Vni. I (13-14)'),
                    ('First_Violin_Staff_VIII', 'Vni. I (15-16)'),
                    ('Second_Violin_Staff_III', 'Vni. II (5-6)'),
                    ('Second_Violin_Staff_IV', 'Vni. II (7-8)'),
                    ('Second_Violin_Staff_IX', 'Vni. II (17-18)'),
                    ('Second_Violin_Staff_V', 'Vni. II (9-10)'),
                    ('Second_Violin_Staff_VI', 'Vni. II (11-12)'),
                    ('Second_Violin_Staff_VII', 'Vni. II (13-14)'),
                    ('Second_Violin_Staff_VIII', 'Vni. II (15-16)'),
                    ('Viola_Staff_III', 'Vle. (5-6)'),
                    ('Viola_Staff_IV', 'Vle. (7-8)'),
                    ('Viola_Staff_IX', 'Vle. (17-18)'),
                    ('Viola_Staff_V', 'Vle. (9-10)'),
                    ('Viola_Staff_VI', 'Vle. (11-12)'),
                    ('Viola_Staff_VII', 'Vle. (13-14)'),
                    ('Viola_Staff_VIII', 'Vle. (15-16)'),
                    ]
                ),
            ),
        ('first_measure_number', 131),
        ('segment_name', 'R'),
        ('segment_number', 19),
        ('start_clock_time', "4'19''"),
        ('stop_clock_time', "4'26''"),
        (
            'time_signatures',
            ['4/4', '2/4', '4/4'],
            ),
        ]
    )
