import abjad


metadata = abjad.OrderedDict(
    [
        (
            'alive_during_segment',
            [
                'Score',
                'Global_Context',
                'Global_Rests',
                'Global_Skips',
                'Music_Context',
                'Percussion_Staff_Group',
                'Percussion_Staff_I',
                'Percussion_Voice_I',
                'Percussion_Rest_Voice_I',
                'String_Staff_Group',
                'FirstViolin_Square_Staff_Group',
                'First_Violin_Staff_I',
                'First_Violin_Voice_I',
                'First_Violin_Rest_Voice_I',
                'First_Violin_Voice_II',
                'First_Violin_Rest_Voice_II',
                'First_Violin_Staff_II',
                'First_Violin_Voice_III',
                'First_Violin_Rest_Voice_III',
                'First_Violin_Voice_IV',
                'First_Violin_Rest_Voice_IV',
                'First_Violin_Staff_III',
                'First_Violin_Voice_V',
                'First_Violin_Rest_Voice_V',
                'First_Violin_Voice_VI',
                'First_Violin_Rest_Voice_VI',
                'First_Violin_Staff_IV',
                'First_Violin_Voice_VII',
                'First_Violin_Rest_Voice_VII',
                'First_Violin_Voice_VIII',
                'First_Violin_Rest_Voice_VIII',
                'First_Violin_Staff_V',
                'First_Violin_Voice_IX',
                'First_Violin_Rest_Voice_IX',
                'First_Violin_Voice_X',
                'First_Violin_Rest_Voice_X',
                'First_Violin_Staff_VI',
                'First_Violin_Voice_XI',
                'First_Violin_Rest_Voice_XI',
                'First_Violin_Voice_XII',
                'First_Violin_Rest_Voice_XII',
                'First_Violin_Staff_VII',
                'First_Violin_Voice_XIII',
                'First_Violin_Rest_Voice_XIII',
                'First_Violin_Voice_XIV',
                'First_Violin_Rest_Voice_XIV',
                'First_Violin_Staff_VIII',
                'First_Violin_Voice_XV',
                'First_Violin_Rest_Voice_XV',
                'First_Violin_Voice_XVI',
                'First_Violin_Rest_Voice_XVI',
                'First_Violin_Staff_IX',
                'First_Violin_Voice_XVII',
                'First_Violin_Rest_Voice_XVII',
                'First_Violin_Voice_XVIII',
                'First_Violin_Rest_Voice_XVIII',
                'SecondViolin_Square_Staff_Group',
                'Second_Violin_Staff_I',
                'Second_Violin_Voice_I',
                'Second_Violin_Rest_Voice_I',
                'Second_Violin_Voice_II',
                'Second_Violin_Rest_Voice_II',
                'Second_Violin_Staff_II',
                'Second_Violin_Voice_III',
                'Second_Violin_Rest_Voice_III',
                'Second_Violin_Voice_IV',
                'Second_Violin_Rest_Voice_IV',
                'Second_Violin_Staff_III',
                'Second_Violin_Voice_V',
                'Second_Violin_Rest_Voice_V',
                'Second_Violin_Voice_VI',
                'Second_Violin_Rest_Voice_VI',
                'Second_Violin_Staff_IV',
                'Second_Violin_Voice_VII',
                'Second_Violin_Rest_Voice_VII',
                'Second_Violin_Voice_VIII',
                'Second_Violin_Rest_Voice_VIII',
                'Second_Violin_Staff_V',
                'Second_Violin_Voice_IX',
                'Second_Violin_Rest_Voice_IX',
                'Second_Violin_Voice_X',
                'Second_Violin_Rest_Voice_X',
                'Second_Violin_Staff_VI',
                'Second_Violin_Voice_XI',
                'Second_Violin_Rest_Voice_XI',
                'Second_Violin_Voice_XII',
                'Second_Violin_Rest_Voice_XII',
                'Second_Violin_Staff_VII',
                'Second_Violin_Voice_XIII',
                'Second_Violin_Rest_Voice_XIII',
                'Second_Violin_Voice_XIV',
                'Second_Violin_Rest_Voice_XIV',
                'Second_Violin_Staff_VIII',
                'Second_Violin_Voice_XV',
                'Second_Violin_Rest_Voice_XV',
                'Second_Violin_Voice_XVI',
                'Second_Violin_Rest_Voice_XVI',
                'Second_Violin_Staff_IX',
                'Second_Violin_Voice_XVII',
                'Second_Violin_Rest_Voice_XVII',
                'Second_Violin_Voice_XVIII',
                'Second_Violin_Rest_Voice_XVIII',
                'Viola_Square_Staff_Group',
                'Viola_Staff_I',
                'Viola_Voice_I',
                'Viola_Rest_Voice_I',
                'Viola_Voice_II',
                'Viola_Rest_Voice_II',
                'Viola_Staff_II',
                'Viola_Voice_III',
                'Viola_Rest_Voice_III',
                'Viola_Voice_IV',
                'Viola_Rest_Voice_IV',
                'Viola_Staff_III',
                'Viola_Voice_V',
                'Viola_Rest_Voice_V',
                'Viola_Voice_VI',
                'Viola_Rest_Voice_VI',
                'Viola_Staff_IV',
                'Viola_Voice_VII',
                'Viola_Rest_Voice_VII',
                'Viola_Voice_VIII',
                'Viola_Rest_Voice_VIII',
                'Viola_Staff_V',
                'Viola_Voice_IX',
                'Viola_Rest_Voice_IX',
                'Viola_Voice_X',
                'Viola_Rest_Voice_X',
                'Viola_Staff_VI',
                'Viola_Voice_XI',
                'Viola_Rest_Voice_XI',
                'Viola_Voice_XII',
                'Viola_Rest_Voice_XII',
                'Viola_Staff_VII',
                'Viola_Voice_XIII',
                'Viola_Rest_Voice_XIII',
                'Viola_Voice_XIV',
                'Viola_Rest_Voice_XIV',
                'Viola_Staff_VIII',
                'Viola_Voice_XV',
                'Viola_Rest_Voice_XV',
                'Viola_Voice_XVI',
                'Viola_Rest_Voice_XVI',
                'Viola_Staff_IX',
                'Viola_Voice_XVII',
                'Viola_Rest_Voice_XVII',
                'Viola_Voice_XVIII',
                'Viola_Rest_Voice_XVIII',
                'Cello_Square_Staff_Group',
                'Cello_Staff_I',
                'Cello_Voice_I',
                'Cello_Rest_Voice_I',
                'Cello_Voice_II',
                'Cello_Rest_Voice_II',
                'Cello_Staff_II',
                'Cello_Voice_III',
                'Cello_Rest_Voice_III',
                'Cello_Voice_IV',
                'Cello_Rest_Voice_IV',
                'Cello_Staff_III',
                'Cello_Voice_V',
                'Cello_Rest_Voice_V',
                'Cello_Voice_VI',
                'Cello_Rest_Voice_VI',
                'Cello_Staff_IV',
                'Cello_Voice_VII',
                'Cello_Rest_Voice_VII',
                'Cello_Voice_VIII',
                'Cello_Rest_Voice_VIII',
                'Cello_Staff_V',
                'Cello_Voice_IX',
                'Cello_Rest_Voice_IX',
                'Cello_Voice_X',
                'Cello_Rest_Voice_X',
                'Cello_Staff_VI',
                'Cello_Voice_XI',
                'Cello_Rest_Voice_XI',
                'Cello_Voice_XII',
                'Cello_Rest_Voice_XII',
                'Cello_Staff_VII',
                'Cello_Voice_XIII',
                'Cello_Rest_Voice_XIII',
                'Cello_Voice_XIV',
                'Cello_Rest_Voice_XIV',
                ],
            ),
        (
            'bol_measure_numbers',
            [161],
            ),
        ('duration', "0'08''"),
        (
            'fermata_measure_numbers',
            [164],
            ),
        ('final_measure_is_fermata', True),
        ('final_measure_number', 164),
        (
            'first_appearance_margin_markup',
            abjad.OrderedDict(
                [
                    ('CelloStaffII', 'Vc. (3-4)'),
                    ('CelloStaffIII', 'Vc. (5-6)'),
                    ('CelloStaffIV', 'Vc. (7-8)'),
                    ('CelloStaffV', 'Vc. (9-10)'),
                    ('CelloStaffVI', 'Vc. (11-12)'),
                    ('CelloStaffVII', 'Vc. (13-14)'),
                    ('ContrabassStaffIII', 'Cb. (5-6)'),
                    ('FirstViolinStaffIV', 'Vni. I (7-8)'),
                    ('FirstViolinStaffIX', 'Vni. I (17-18)'),
                    ('FirstViolinStaffV', 'Vni. I (9-10)'),
                    ('FirstViolinStaffVI', 'Vni. I (11-12)'),
                    ('FirstViolinStaffVII', 'Vni. I (13-14)'),
                    ('FirstViolinStaffVIII', 'Vni. I (15-16)'),
                    ('SecondViolinStaffIII', 'Vni. II (5-6)'),
                    ('SecondViolinStaffIV', 'Vni. II (7-8)'),
                    ('SecondViolinStaffIX', 'Vni. II (17-18)'),
                    ('SecondViolinStaffV', 'Vni. II (9-10)'),
                    ('SecondViolinStaffVI', 'Vni. II (11-12)'),
                    ('SecondViolinStaffVII', 'Vni. II (13-14)'),
                    ('SecondViolinStaffVIII', 'Vni. II (15-16)'),
                    ('ViolaStaffIII', 'Vle. (5-6)'),
                    ('ViolaStaffIV', 'Vle. (7-8)'),
                    ('ViolaStaffIX', 'Vle. (17-18)'),
                    ('ViolaStaffV', 'Vle. (9-10)'),
                    ('ViolaStaffVI', 'Vle. (11-12)'),
                    ('ViolaStaffVII', 'Vle. (13-14)'),
                    ('ViolaStaffVIII', 'Vle. (15-16)'),
                    ]
                ),
            ),
        ('first_measure_number', 161),
        ('segment_name', 'AB'),
        ('segment_number', 29),
        ('start_clock_time', "5'39''"),
        ('stop_clock_time', "5'47''"),
        (
            'time_signatures',
            ['2/4', '4/4', '4/4', '1/4'],
            ),
        ]
    )
