import abjad


metadata = abjad.OrderedDict(
    [
        (
            'bol_measure_numbers',
            [7],
            ),
        ('duration', "0'09''"),
        ('first_measure_number', 7),
        ('last_measure_number', 12),
        (
            'persistent_indicators',
            abjad.OrderedDict(
                [
                    (
                        'CellosStaffI',
                        [
                            abjad.Momento(
                                context='CellosVoiceI',
                                prototype='abjad.Clef',
                                value='tenor',
                                ),
                            abjad.Momento(
                                context='CellosVoiceI',
                                prototype='abjad.Instrument',
                                value='Cello',
                                ),
                            abjad.Momento(
                                context='CellosVoiceI',
                                prototype='abjad.MarginMarkup',
                                value='Vc.',
                                ),
                            ],
                        ),
                    (
                        'CellosVoiceI',
                        [
                            abjad.Momento(
                                context='CellosVoiceI',
                                prototype='abjad.Dynamic',
                                value='\\p_sub_but_accents_continue_sffz',
                                ),
                            ],
                        ),
                    (
                        'FirstViolinsStaffI',
                        [
                            abjad.Momento(
                                context='FirstViolinsVoiceI',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='FirstViolinsVoiceI',
                                prototype='abjad.Instrument',
                                value='Violin',
                                ),
                            abjad.Momento(
                                context='FirstViolinsVoiceI',
                                prototype='abjad.MarginMarkup',
                                value='Vni. I (1-10)',
                                ),
                            ],
                        ),
                    (
                        'FirstViolinsStaffII',
                        [
                            abjad.Momento(
                                context='FirstViolinsVoiceII',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='FirstViolinsVoiceII',
                                prototype='abjad.Instrument',
                                value='Violin',
                                ),
                            abjad.Momento(
                                context='FirstViolinsVoiceII',
                                prototype='abjad.MarginMarkup',
                                value='Vni. I (11-18)',
                                ),
                            ],
                        ),
                    (
                        'FirstViolinsVoiceI',
                        [
                            abjad.Momento(
                                context='FirstViolinsVoiceI',
                                prototype='abjad.Dynamic',
                                value='\\p_sub_but_accents_continue_sffz',
                                ),
                            ],
                        ),
                    (
                        'FirstViolinsVoiceII',
                        [
                            abjad.Momento(
                                context='FirstViolinsVoiceII',
                                prototype='abjad.Dynamic',
                                value='\\p_sub_but_accents_continue_sffz',
                                ),
                            ],
                        ),
                    (
                        'Score',
                        [
                            abjad.Momento(
                                context='GlobalSkips',
                                prototype='abjad.MetronomeMark',
                                value='114',
                                ),
                            abjad.Momento(
                                context='GlobalSkips',
                                prototype='abjad.TimeSignature',
                                value='2/4',
                                ),
                            ],
                        ),
                    (
                        'SecondViolinsStaffI',
                        [
                            abjad.Momento(
                                context='SecondViolinsVoiceI',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='SecondViolinsVoiceI',
                                prototype='abjad.Instrument',
                                value='Violin',
                                ),
                            abjad.Momento(
                                context='SecondViolinsVoiceI',
                                prototype='abjad.MarginMarkup',
                                value='Vni. II (1-10)',
                                ),
                            ],
                        ),
                    (
                        'SecondViolinsStaffII',
                        [
                            abjad.Momento(
                                context='SecondViolinsVoiceII',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='SecondViolinsVoiceII',
                                prototype='abjad.Instrument',
                                value='Violin',
                                ),
                            abjad.Momento(
                                context='SecondViolinsVoiceII',
                                prototype='abjad.MarginMarkup',
                                value='Vni. II (11-18)',
                                ),
                            ],
                        ),
                    (
                        'SecondViolinsVoiceI',
                        [
                            abjad.Momento(
                                context='SecondViolinsVoiceI',
                                prototype='abjad.Dynamic',
                                value='\\p_sub_but_accents_continue_sffz',
                                ),
                            ],
                        ),
                    (
                        'SecondViolinsVoiceII',
                        [
                            abjad.Momento(
                                context='SecondViolinsVoiceII',
                                prototype='abjad.Dynamic',
                                value='\\p_sub_but_accents_continue_sffz',
                                ),
                            ],
                        ),
                    (
                        'ViolasStaffI',
                        [
                            abjad.Momento(
                                context='ViolasVoiceI',
                                prototype='abjad.Clef',
                                value='alto',
                                ),
                            abjad.Momento(
                                context='ViolasVoiceI',
                                prototype='abjad.Instrument',
                                value='Viola',
                                ),
                            abjad.Momento(
                                context='ViolasVoiceI',
                                prototype='abjad.MarginMarkup',
                                value='Vle. (1-10)',
                                ),
                            ],
                        ),
                    (
                        'ViolasStaffII',
                        [
                            abjad.Momento(
                                context='ViolasVoiceII',
                                prototype='abjad.Clef',
                                value='alto',
                                ),
                            abjad.Momento(
                                context='ViolasVoiceII',
                                prototype='abjad.Instrument',
                                value='Viola',
                                ),
                            abjad.Momento(
                                context='ViolasVoiceII',
                                prototype='abjad.MarginMarkup',
                                value='Vle. (11-18)',
                                ),
                            ],
                        ),
                    (
                        'ViolasVoiceI',
                        [
                            abjad.Momento(
                                context='ViolasVoiceI',
                                prototype='abjad.Dynamic',
                                value='\\p_sub_but_accents_continue_sffz',
                                ),
                            ],
                        ),
                    (
                        'ViolasVoiceII',
                        [
                            abjad.Momento(
                                context='ViolasVoiceII',
                                prototype='abjad.Dynamic',
                                value='\\p_sub_but_accents_continue_sffz',
                                ),
                            ],
                        ),
                    ]
                ),
            ),
        ('segment_name', '_2'),
        ('segment_number', 2),
        (
            'sounds_during_segment',
            abjad.OrderedDict(
                [
                    ('FirstViolinsVoiceI', True),
                    ('FirstViolinsVoiceII', True),
                    ('SecondViolinsVoiceI', True),
                    ('SecondViolinsVoiceII', True),
                    ('ViolasVoiceI', True),
                    ('ViolasVoiceII', True),
                    ('CellosVoiceI', True),
                    ]
                ),
            ),
        ('start_clock_time', "0'11''"),
        ('stop_clock_time', "0'20''"),
        (
            'time_signatures',
            ['4/4', '2/4', '3/4', '3/4', '4/4', '2/4'],
            ),
        (
            'voice_metadata',
            abjad.OrderedDict(
                [
                    (
                        'FirstViolinsVoiceI',
                        abjad.OrderedDict(
                            [
                                (
                                    'sforzando_exchange_rhythm',
                                    [
                                        ('talea_weight_consumed', 108),
                                        ],
                                    ),
                                ]
                            ),
                        ),
                    (
                        'FirstViolinsVoiceII',
                        abjad.OrderedDict(
                            [
                                (
                                    'sforzando_exchange_rhythm',
                                    [
                                        ('talea_weight_consumed', 108),
                                        ],
                                    ),
                                ]
                            ),
                        ),
                    (
                        'SecondViolinsVoiceI',
                        abjad.OrderedDict(
                            [
                                (
                                    'sforzando_exchange_rhythm',
                                    [
                                        ('talea_weight_consumed', 108),
                                        ],
                                    ),
                                ]
                            ),
                        ),
                    (
                        'SecondViolinsVoiceII',
                        abjad.OrderedDict(
                            [
                                (
                                    'sforzando_exchange_rhythm',
                                    [
                                        ('talea_weight_consumed', 108),
                                        ],
                                    ),
                                ]
                            ),
                        ),
                    (
                        'ViolasVoiceI',
                        abjad.OrderedDict(
                            [
                                (
                                    'sforzando_exchange_rhythm',
                                    [
                                        ('talea_weight_consumed', 108),
                                        ],
                                    ),
                                ]
                            ),
                        ),
                    (
                        'ViolasVoiceII',
                        abjad.OrderedDict(
                            [
                                (
                                    'sforzando_exchange_rhythm',
                                    [
                                        ('talea_weight_consumed', 108),
                                        ],
                                    ),
                                ]
                            ),
                        ),
                    (
                        'CellosVoiceI',
                        abjad.OrderedDict(
                            [
                                (
                                    'sforzando_exchange_rhythm',
                                    [
                                        ('talea_weight_consumed', 108),
                                        ],
                                    ),
                                ]
                            ),
                        ),
                    ]
                ),
            ),
        ]
    )
