import abjad


metadata = abjad.OrderedDict(
    [
        (
            'alive_during_segment',
            [
                'Score',
                'Global_Context',
                'Global_Rests',
                'Global_Skips',
                'Music_Context',
                'Wind_Staff_Group',
                'Flute_Square_Staff_Group',
                'Flute_Staff_I',
                'Flute_Voice_I',
                'Flute_Rest_Voice_I',
                'Flute_Voice_III',
                'Flute_Rest_Voice_III',
                'Flute_Staff_II',
                'Flute_Voice_II',
                'Flute_Rest_Voice_II',
                'Flute_Voice_IV',
                'Flute_Rest_Voice_IV',
                'ClarinetFamily_Square_Staff_Group',
                'Clarinet_Staff_I',
                'Clarinet_Voice_I',
                'Clarinet_Rest_Voice_I',
                'Bass_Clarinet_Staff_I',
                'Bass_Clarinet_Voice_I',
                'Piano_Piano_Staff',
                'Piano_Staff_I',
                'Piano_Voice_I',
                'Harp_Piano_Staff',
                'Harp_Staff_I',
                'Harp_Voice_I',
                'Percussion_Staff_Group',
                'Percussion_Staff_I',
                'Percussion_Voice_I',
                'Percussion_Rest_Voice_I',
                'Percussion_Staff_II',
                'Percussion_Voice_II',
                'Percussion_Rest_Voice_II',
                'Percussion_Staff_III',
                'Percussion_Voice_III',
                'String_Staff_Group',
                'First_Violin_Staff_I',
                'First_Violin_Voice_III',
                'First_Violin_Rest_Voice_III',
                'First_Violin_Voice_I',
                'First_Violin_Rest_Voice_I',
                'Second_Violin_Staff_I',
                'Second_Violin_Voice_I',
                'Second_Violin_Rest_Voice_I',
                'Viola_Staff_I',
                'Viola_Voice_I',
                'Viola_Rest_Voice_I',
                'Cello_Staff_I',
                'Cello_Voice_I',
                'Cello_Rest_Voice_I',
                'Contrabass_Square_Staff_Group',
                'Contrabass_Staff_I',
                'Contrabass_Voice_I',
                'Contrabass_Staff_II',
                'Contrabass_Voice_III',
                'Contrabass_Rest_Voice_III',
                ],
            ),
        (
            'bol_measure_numbers',
            [82],
            ),
        ('duration', "0'11''"),
        ('final_measure_number', 87),
        (
            'first_appearance_margin_markup',
            abjad.OrderedDict(
                [
                    ('Flute_Staff_I', 'Fl. (1+3)'),
                    ('Flute_Staff_II', 'Fl. (2+4)'),
                    ]
                ),
            ),
        ('first_measure_number', 82),
        ('segment_name', 'M'),
        ('segment_number', 14),
        ('start_clock_time', "2'47''"),
        ('stop_clock_time', "2'58''"),
        (
            'time_signatures',
            ['3/4', '4/4', '2/4', '4/4', '4/4', '4/4'],
            ),
        ]
    )
