import abjad


metadata = abjad.OrderedDict(
    [
        (
            'ARCH_A_PARTS_BCL',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_BSN_1',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_BSN_2',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_CB_1',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_CB_2',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_CB_3',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_CB_4',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_CB_5',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_CB_6',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_CL_1',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_CL_2',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_CL_3',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_EH',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_FL_1',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_FL_2',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_FL_3',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_HN_1',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_HN_2',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_HN_3',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_HN_4',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_HP',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_OB_1',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_OB_2',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_OB_3',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_PERC_1',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_PERC_2',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_PERC_3',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_PERC_4',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_PF',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_PICC',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_TBN_1',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_TBN_2',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_TBN_3',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_TBN_4',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_TP_1',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_TP_2',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_TP_3',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_TP_4',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_TUB',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VA_1',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VA_10',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VA_11',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VA_12',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VA_13',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VA_14',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VA_15',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VA_16',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VA_17',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VA_18',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VA_2',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VA_3',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VA_4',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VA_5',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VA_6',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VA_7',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VA_8',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VA_9',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VC_1',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VC_10',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VC_11',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VC_12',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VC_13',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VC_14',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VC_2',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VC_3',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VC_4',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VC_5',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VC_6',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VC_7',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VC_8',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VC_9',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VN_1_1',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 23, 28, 34],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VN_1_10',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VN_1_11',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VN_1_12',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VN_1_13',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VN_1_14',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VN_1_15',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VN_1_16',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VN_1_17',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VN_1_18',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VN_1_2',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24, 30, 37],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VN_1_3',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VN_1_4',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VN_1_5',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VN_1_6',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VN_1_7',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VN_1_8',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VN_1_9',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VN_2_1',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VN_2_10',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VN_2_11',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VN_2_12',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VN_2_13',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VN_2_14',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VN_2_15',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VN_2_16',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VN_2_17',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VN_2_18',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VN_2_2',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VN_2_3',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VN_2_4',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VN_2_5',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VN_2_6',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VN_2_7',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VN_2_8',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        (
            'ARCH_A_PARTS_VN_2_9',
            abjad.OrderedDict(
                [
                    (
                        'bol_measure_numbers',
                        [1, 7, 13, 18, 24],
                        ),
                    ]
                ),
            ),
        ('catalog_number_suffix', 'ARCH-A'),
        ('paper_size', 'arch a'),
        ('parts_directory', True),
        ]
    )
