import abjad


metadata = abjad.OrderedDict(
    [
        ('duration', "0'14''"),
        ('first_measure_number', 13),
        ('last_measure_number', 20),
        (
            'persistent_indicators',
            abjad.OrderedDict(
                [
                    (
                        'CellosStaffI',
                        [
                            abjad.Momento(
                                context='CellosVoiceI',
                                prototype='abjad.Clef',
                                value='tenor',
                                ),
                            abjad.Momento(
                                context='CellosVoiceI',
                                prototype='abjad.Instrument',
                                value='Cello',
                                ),
                            abjad.Momento(
                                context='CellosVoiceI',
                                prototype='baca.MarginMarkup',
                                value='Vc.',
                                ),
                            ],
                        ),
                    (
                        'CellosVoiceI',
                        [
                            abjad.Momento(
                                context='CellosVoiceI',
                                prototype='abjad.Dynamic',
                                value='\\p_sub_but_accents_continue_sffz',
                                ),
                            ],
                        ),
                    (
                        'FirstViolinsStaffI',
                        [
                            abjad.Momento(
                                context='FirstViolinsVoiceI',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='FirstViolinsVoiceI',
                                prototype='abjad.Instrument',
                                value='Violin',
                                ),
                            abjad.Momento(
                                context='FirstViolinsVoiceI',
                                prototype='baca.MarginMarkup',
                                value='Vni. I (1-10)',
                                ),
                            ],
                        ),
                    (
                        'FirstViolinsVoiceI',
                        [
                            abjad.Momento(
                                context='FirstViolinsVoiceI',
                                prototype='abjad.Dynamic',
                                value='\\p_sub_but_accents_continue_sffz',
                                ),
                            ],
                        ),
                    (
                        'Score',
                        [
                            abjad.Momento(
                                context='GlobalSkips',
                                prototype='abjad.MetronomeMark',
                                value='114',
                                ),
                            abjad.Momento(
                                context='GlobalSkips',
                                prototype='abjad.TimeSignature',
                                value='2/4',
                                ),
                            ],
                        ),
                    (
                        'SecondViolinsStaffI',
                        [
                            abjad.Momento(
                                context='SecondViolinsVoiceI',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='SecondViolinsVoiceI',
                                prototype='abjad.Instrument',
                                value='Violin',
                                ),
                            abjad.Momento(
                                context='SecondViolinsVoiceI',
                                prototype='baca.MarginMarkup',
                                value='Vni. II (1-10)',
                                ),
                            ],
                        ),
                    (
                        'SecondViolinsStaffII',
                        [
                            abjad.Momento(
                                context='SecondViolinsVoiceII',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='SecondViolinsVoiceII',
                                prototype='abjad.Instrument',
                                value='Violin',
                                ),
                            abjad.Momento(
                                context='SecondViolinsVoiceII',
                                prototype='baca.MarginMarkup',
                                value='Vni. II (11-18)',
                                ),
                            ],
                        ),
                    (
                        'SecondViolinsVoiceI',
                        [
                            abjad.Momento(
                                context='SecondViolinsVoiceI',
                                prototype='abjad.Dynamic',
                                value='\\p_sub_but_accents_continue_sffz',
                                ),
                            ],
                        ),
                    (
                        'SecondViolinsVoiceII',
                        [
                            abjad.Momento(
                                context='SecondViolinsVoiceII',
                                prototype='abjad.Dynamic',
                                value='\\p_sub_but_accents_continue_sffz',
                                ),
                            ],
                        ),
                    (
                        'ViolasStaffI',
                        [
                            abjad.Momento(
                                context='ViolasVoiceI',
                                prototype='abjad.Clef',
                                value='alto',
                                ),
                            abjad.Momento(
                                context='ViolasVoiceI',
                                prototype='abjad.Instrument',
                                value='Viola',
                                ),
                            abjad.Momento(
                                context='ViolasVoiceI',
                                prototype='baca.MarginMarkup',
                                value='Vle. (1-10)',
                                ),
                            ],
                        ),
                    (
                        'ViolasVoiceI',
                        [
                            abjad.Momento(
                                context='ViolasVoiceI',
                                prototype='abjad.Dynamic',
                                value='\\p_sub_but_accents_continue_sffz',
                                ),
                            ],
                        ),
                    ]
                ),
            ),
        ('segment_number', 3),
        (
            'sounds_during_segment',
            abjad.OrderedDict(
                [
                    ('PiccoloVoiceI', False),
                    ('FlutesVoiceI', False),
                    ('FlutesVoiceII', False),
                    ('FirstViolinsVoiceI', False),
                    ('SecondViolinsVoiceI', False),
                    ('SecondViolinsVoiceII', False),
                    ('ViolasVoiceI', False),
                    ('CellosVoiceI', False),
                    ('ContrabassesVoiceI', False),
                    ]
                ),
            ),
        ('start_clock_time', "0'20''"),
        ('stop_clock_time', "0'34''"),
        (
            'time_signatures',
            [
                '4/4',
                '4/4',
                '4/4',
                '3/4',
                '3/4',
                '4/4',
                '4/4',
                '2/4',
                ],
            ),
        (
            'voice_metadata',
            abjad.OrderedDict(
                [
                    (
                        'PiccoloVoiceI',
                        abjad.OrderedDict(
                            []
                            ),
                        ),
                    (
                        'FlutesVoiceI',
                        abjad.OrderedDict(
                            []
                            ),
                        ),
                    (
                        'FlutesVoiceII',
                        abjad.OrderedDict(
                            []
                            ),
                        ),
                    (
                        'FirstViolinsVoiceI',
                        abjad.OrderedDict(
                            []
                            ),
                        ),
                    (
                        'SecondViolinsVoiceI',
                        abjad.OrderedDict(
                            []
                            ),
                        ),
                    (
                        'SecondViolinsVoiceII',
                        abjad.OrderedDict(
                            []
                            ),
                        ),
                    (
                        'ViolasVoiceI',
                        abjad.OrderedDict(
                            []
                            ),
                        ),
                    (
                        'CellosVoiceI',
                        abjad.OrderedDict(
                            []
                            ),
                        ),
                    (
                        'ContrabassesVoiceI',
                        abjad.OrderedDict(
                            []
                            ),
                        ),
                    ]
                ),
            ),
        ]
    )
