import abjad


metadata = abjad.OrderedDict(
    [
        (
            'alive_during_segment',
            [
                'Score',
                'GlobalContext',
                'GlobalRests',
                'GlobalSkips',
                'MusicContext',
                'StringStaffGroup',
                'FirstViolinSquareStaffGroup',
                'FirstViolinStaffI',
                'FirstViolinVoiceI',
                'FirstViolinVoiceIII',
                'FirstViolinStaffII',
                'FirstViolinVoiceII',
                'FirstViolinVoiceIV',
                'FirstViolinStaffIII',
                'FirstViolinVoiceV',
                'FirstViolinVoiceVI',
                'FirstViolinStaffIV',
                'FirstViolinVoiceVII',
                'FirstViolinVoiceVIII',
                'FirstViolinStaffV',
                'FirstViolinVoiceIX',
                'FirstViolinVoiceX',
                'FirstViolinStaffVI',
                'FirstViolinVoiceXI',
                'FirstViolinVoiceXII',
                'FirstViolinStaffVII',
                'FirstViolinVoiceXIII',
                'FirstViolinVoiceXIV',
                'FirstViolinStaffVIII',
                'FirstViolinVoiceXV',
                'FirstViolinVoiceXVI',
                'FirstViolinStaffIX',
                'FirstViolinVoiceXVII',
                'FirstViolinVoiceXVIII',
                'SecondViolinSquareStaffGroup',
                'SecondViolinStaffI',
                'SecondViolinVoiceI',
                'SecondViolinVoiceIII',
                'SecondViolinStaffII',
                'SecondViolinVoiceII',
                'SecondViolinVoiceIV',
                'SecondViolinStaffIII',
                'SecondViolinVoiceV',
                'SecondViolinVoiceVI',
                'SecondViolinStaffIV',
                'SecondViolinVoiceVII',
                'SecondViolinVoiceVIII',
                'SecondViolinStaffV',
                'SecondViolinVoiceIX',
                'SecondViolinVoiceX',
                'SecondViolinStaffVI',
                'SecondViolinVoiceXI',
                'SecondViolinVoiceXII',
                'SecondViolinStaffVII',
                'SecondViolinVoiceXIII',
                'SecondViolinVoiceXIV',
                'SecondViolinStaffVIII',
                'SecondViolinVoiceXV',
                'SecondViolinVoiceXVI',
                'SecondViolinStaffIX',
                'SecondViolinVoiceXVII',
                'SecondViolinVoiceXVIII',
                'ViolaSquareStaffGroup',
                'ViolaStaffI',
                'ViolaVoiceI',
                'ViolaVoiceIII',
                'ViolaStaffII',
                'ViolaVoiceII',
                'ViolaVoiceIV',
                'ViolaStaffIII',
                'ViolaVoiceV',
                'ViolaVoiceVI',
                'ViolaStaffIV',
                'ViolaVoiceVII',
                'ViolaVoiceVIII',
                'ViolaStaffV',
                'ViolaVoiceIX',
                'ViolaVoiceX',
                'ViolaStaffVI',
                'ViolaVoiceXI',
                'ViolaVoiceXII',
                'ViolaStaffVII',
                'ViolaVoiceXIII',
                'ViolaVoiceXIV',
                'ViolaStaffVIII',
                'ViolaVoiceXV',
                'ViolaVoiceXVI',
                'ViolaStaffIX',
                'ViolaVoiceXVII',
                'ViolaVoiceXVIII',
                'CelloSquareStaffGroup',
                'CelloStaffI',
                'CelloVoiceI',
                'CelloVoiceII',
                'CelloStaffII',
                'CelloVoiceIII',
                'CelloVoiceIV',
                'CelloStaffIII',
                'CelloVoiceV',
                'CelloVoiceVI',
                'CelloStaffIV',
                'CelloVoiceVII',
                'CelloVoiceVIII',
                'CelloStaffV',
                'CelloVoiceIX',
                'CelloVoiceX',
                'CelloStaffVI',
                'CelloVoiceXI',
                'CelloVoiceXII',
                'CelloStaffVII',
                'CelloVoiceXIII',
                'CelloVoiceXIV',
                'ContrabassSquareStaffGroup',
                'ContrabassStaffI',
                'ContrabassVoiceI',
                'ContrabassVoiceII',
                'ContrabassStaffII',
                'ContrabassVoiceIII',
                'ContrabassVoiceIV',
                'ContrabassStaffIII',
                'ContrabassVoiceV',
                'ContrabassVoiceVI',
                ],
            ),
        (
            'bol_measure_numbers',
            [131],
            ),
        (
            'container_to_part_assignment',
            abjad.OrderedDict(
                [
                    (
                        'O_a_ContrabassVoiceIII_a',
                        (
                            abjad.PartAssignment('Contrabass', 3),
                            abjad.Timespan(
                                start_offset=abjad.Offset(0, 1),
                                stop_offset=abjad.Offset(7, 2),
                                ),
                            ),
                        ),
                    (
                        'O_a_ContrabassVoiceII_a',
                        (
                            abjad.PartAssignment('Contrabass', 2),
                            abjad.Timespan(
                                start_offset=abjad.Offset(0, 1),
                                stop_offset=abjad.Offset(7, 2),
                                ),
                            ),
                        ),
                    (
                        'O_a_ContrabassVoiceIV_a',
                        (
                            abjad.PartAssignment('Contrabass', 4),
                            abjad.Timespan(
                                start_offset=abjad.Offset(0, 1),
                                stop_offset=abjad.Offset(7, 2),
                                ),
                            ),
                        ),
                    (
                        'O_a_ContrabassVoiceI_a',
                        (
                            abjad.PartAssignment('Contrabass', 1),
                            abjad.Timespan(
                                start_offset=abjad.Offset(0, 1),
                                stop_offset=abjad.Offset(7, 2),
                                ),
                            ),
                        ),
                    (
                        'O_a_ContrabassVoiceVI_a',
                        (
                            abjad.PartAssignment('Contrabass', 6),
                            abjad.Timespan(
                                start_offset=abjad.Offset(0, 1),
                                stop_offset=abjad.Offset(7, 2),
                                ),
                            ),
                        ),
                    (
                        'O_a_ContrabassVoiceV_a',
                        (
                            abjad.PartAssignment('Contrabass', 5),
                            abjad.Timespan(
                                start_offset=abjad.Offset(0, 1),
                                stop_offset=abjad.Offset(7, 2),
                                ),
                            ),
                        ),
                    ]
                ),
            ),
        ('duration', "0'11''"),
        (
            'fermata_measure_numbers',
            [121, 126],
            ),
        (
            'first_appearance_margin_markup',
            abjad.OrderedDict(
                [
                    ('CelloStaffII', 'Vc.'),
                    ('CelloStaffIII', 'Vc.'),
                    ('CelloStaffIV', 'Vc.'),
                    ('CelloStaffV', 'Vc.'),
                    ('CelloStaffVI', 'Vc.'),
                    ('CelloStaffVII', 'Vc.'),
                    ('ContrabassStaffIII', 'Cb.'),
                    ('FirstViolinStaffIV', 'Vni. I'),
                    ('FirstViolinStaffIX', 'Vni. I'),
                    ('FirstViolinStaffV', 'Vni. I'),
                    ('FirstViolinStaffVI', 'Vni. I'),
                    ('FirstViolinStaffVII', 'Vni. I'),
                    ('FirstViolinStaffVIII', 'Vni. I'),
                    ('SecondViolinStaffIII', 'Vni. II'),
                    ('SecondViolinStaffIV', 'Vni. II'),
                    ('SecondViolinStaffIX', 'Vni. II'),
                    ('SecondViolinStaffV', 'Vni. II'),
                    ('SecondViolinStaffVI', 'Vni. II'),
                    ('SecondViolinStaffVII', 'Vni. II'),
                    ('SecondViolinStaffVIII', 'Vni. II'),
                    ('ViolaStaffIII', 'Vle.'),
                    ('ViolaStaffIV', 'Vle.'),
                    ('ViolaStaffIX', 'Vle.'),
                    ('ViolaStaffV', 'Vle.'),
                    ('ViolaStaffVI', 'Vle.'),
                    ('ViolaStaffVII', 'Vle.'),
                    ('ViolaStaffVIII', 'Vle.'),
                    ]
                ),
            ),
        ('first_measure_number', 131),
        ('last_measure_is_fermata', True),
        ('last_measure_number', 134),
        (
            'persistent_indicators',
            abjad.OrderedDict(
                [
                    (
                        'BassClarinetStaffI',
                        [
                            abjad.Momento(
                                context='BassClarinetVoiceI',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='BassClarinetVoiceI',
                                prototype='abjad.Instrument',
                                value='BassClarinet',
                                ),
                            abjad.Momento(
                                context='BassClarinetVoiceI',
                                prototype='abjad.MarginMarkup',
                                value='B. cl.',
                                ),
                            ],
                        ),
                    (
                        'BassClarinetVoiceI',
                        [
                            abjad.Momento(
                                context='BassClarinetVoiceI',
                                prototype='abjad.Dynamic',
                                value='p',
                                ),
                            ],
                        ),
                    (
                        'BassoonStaffI',
                        [
                            abjad.Momento(
                                context='BassoonVoiceI',
                                prototype='abjad.Clef',
                                value='bass',
                                ),
                            abjad.Momento(
                                context='BassoonVoiceII',
                                prototype='abjad.Instrument',
                                value='Bassoon',
                                ),
                            abjad.Momento(
                                context='BassoonVoiceII',
                                prototype='abjad.MarginMarkup',
                                value='Bsn.',
                                ),
                            ],
                        ),
                    (
                        'BassoonVoiceI',
                        [
                            abjad.Momento(
                                context='BassoonVoiceI',
                                edition=abjad.Tag('+PARTS'),
                                prototype='abjad.Dynamic',
                                value='niente',
                                ),
                            ],
                        ),
                    (
                        'BassoonVoiceII',
                        [
                            abjad.Momento(
                                context='BassoonVoiceII',
                                prototype='abjad.Dynamic',
                                value='niente',
                                ),
                            ],
                        ),
                    (
                        'CelloStaffI',
                        [
                            abjad.Momento(
                                context='CelloVoiceI',
                                prototype='abjad.Clef',
                                value='bass',
                                ),
                            abjad.Momento(
                                context='CelloVoiceI',
                                prototype='abjad.Instrument',
                                value='Cello',
                                ),
                            abjad.Momento(
                                context='CelloVoiceI',
                                prototype='abjad.MarginMarkup',
                                value='Vc. (1-8) (9-14)',
                                ),
                            ],
                        ),
                    (
                        'CelloStaffII',
                        [
                            abjad.Momento(
                                context='CelloVoiceIII',
                                prototype='abjad.Clef',
                                value='bass',
                                ),
                            abjad.Momento(
                                context='CelloVoiceIII',
                                prototype='abjad.Instrument',
                                value='Cello',
                                ),
                            abjad.Momento(
                                context='CelloVoiceIII',
                                prototype='abjad.MarginMarkup',
                                value='Vc.',
                                ),
                            ],
                        ),
                    (
                        'CelloStaffIII',
                        [
                            abjad.Momento(
                                context='CelloVoiceV',
                                prototype='abjad.Clef',
                                value='bass',
                                ),
                            abjad.Momento(
                                context='CelloVoiceV',
                                prototype='abjad.Instrument',
                                value='Cello',
                                ),
                            abjad.Momento(
                                context='CelloVoiceV',
                                prototype='abjad.MarginMarkup',
                                value='Vc.',
                                ),
                            ],
                        ),
                    (
                        'CelloStaffIV',
                        [
                            abjad.Momento(
                                context='CelloVoiceVII',
                                prototype='abjad.Clef',
                                value='bass',
                                ),
                            abjad.Momento(
                                context='CelloVoiceVII',
                                prototype='abjad.Instrument',
                                value='Cello',
                                ),
                            abjad.Momento(
                                context='CelloVoiceVII',
                                prototype='abjad.MarginMarkup',
                                value='Vc.',
                                ),
                            ],
                        ),
                    (
                        'CelloStaffV',
                        [
                            abjad.Momento(
                                context='CelloVoiceIX',
                                prototype='abjad.Clef',
                                value='bass',
                                ),
                            abjad.Momento(
                                context='CelloVoiceIX',
                                prototype='abjad.Instrument',
                                value='Cello',
                                ),
                            abjad.Momento(
                                context='CelloVoiceIX',
                                prototype='abjad.MarginMarkup',
                                value='Vc.',
                                ),
                            ],
                        ),
                    (
                        'CelloStaffVI',
                        [
                            abjad.Momento(
                                context='CelloVoiceXI',
                                prototype='abjad.Clef',
                                value='bass',
                                ),
                            abjad.Momento(
                                context='CelloVoiceXI',
                                prototype='abjad.Instrument',
                                value='Cello',
                                ),
                            abjad.Momento(
                                context='CelloVoiceXI',
                                prototype='abjad.MarginMarkup',
                                value='Vc.',
                                ),
                            ],
                        ),
                    (
                        'CelloStaffVII',
                        [
                            abjad.Momento(
                                context='CelloVoiceXIII',
                                prototype='abjad.Clef',
                                value='bass',
                                ),
                            abjad.Momento(
                                context='CelloVoiceXIII',
                                prototype='abjad.Instrument',
                                value='Cello',
                                ),
                            abjad.Momento(
                                context='CelloVoiceXIII',
                                prototype='abjad.MarginMarkup',
                                value='Vc.',
                                ),
                            ],
                        ),
                    (
                        'CelloVoiceI',
                        [
                            abjad.Momento(
                                context='CelloVoiceI',
                                prototype='abjad.Dynamic',
                                value='niente',
                                ),
                            ],
                        ),
                    (
                        'CelloVoiceII',
                        [
                            abjad.Momento(
                                context='CelloVoiceII',
                                prototype='abjad.Dynamic',
                                value='niente',
                                ),
                            ],
                        ),
                    (
                        'ClarinetStaffI',
                        [
                            abjad.Momento(
                                context='ClarinetVoiceI',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='ClarinetVoiceI',
                                prototype='abjad.Instrument',
                                value='Clarinet',
                                ),
                            abjad.Momento(
                                context='ClarinetVoiceI',
                                prototype='abjad.MarginMarkup',
                                value='Cl. 1',
                                ),
                            ],
                        ),
                    (
                        'ClarinetVoiceI',
                        [
                            abjad.Momento(
                                context='ClarinetVoiceI',
                                prototype='abjad.Dynamic',
                                value='ff',
                                ),
                            ],
                        ),
                    (
                        'ContrabassStaffI',
                        [
                            abjad.Momento(
                                context='ContrabassVoiceI',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='ContrabassVoiceI',
                                prototype='abjad.Instrument',
                                value='Contrabass',
                                ),
                            abjad.Momento(
                                context='ContrabassVoiceI',
                                prototype='abjad.MarginMarkup',
                                value='Cb. 1',
                                ),
                            abjad.Momento(
                                context='ContrabassVoiceII',
                                prototype='baca.StaffLines',
                                value=2,
                                ),
                            ],
                        ),
                    (
                        'ContrabassStaffII',
                        [
                            abjad.Momento(
                                context='ContrabassVoiceIII',
                                prototype='abjad.Clef',
                                value='bass',
                                ),
                            abjad.Momento(
                                context='ContrabassVoiceIII',
                                prototype='abjad.Instrument',
                                value='Contrabass',
                                ),
                            abjad.Momento(
                                context='ContrabassVoiceIII',
                                prototype='abjad.MarginMarkup',
                                value='Cb.',
                                ),
                            abjad.Momento(
                                context='ContrabassVoiceIV',
                                prototype='baca.StaffLines',
                                value=2,
                                ),
                            ],
                        ),
                    (
                        'ContrabassStaffIII',
                        [
                            abjad.Momento(
                                context='ContrabassVoiceV',
                                prototype='abjad.Clef',
                                value='bass',
                                ),
                            abjad.Momento(
                                context='ContrabassVoiceVI',
                                prototype='abjad.Instrument',
                                value='Contrabass',
                                ),
                            abjad.Momento(
                                context='ContrabassVoiceVI',
                                prototype='abjad.MarginMarkup',
                                value='Cb.',
                                ),
                            abjad.Momento(
                                context='ContrabassVoiceVI',
                                prototype='baca.StaffLines',
                                value=2,
                                ),
                            ],
                        ),
                    (
                        'ContrabassVoiceI',
                        [
                            abjad.Momento(
                                context='ContrabassVoiceI',
                                prototype='abjad.Dynamic',
                                value='mf',
                                ),
                            ],
                        ),
                    (
                        'ContrabassVoiceIII',
                        [
                            abjad.Momento(
                                context='ContrabassVoiceIII',
                                prototype='abjad.Dynamic',
                                value='niente',
                                ),
                            ],
                        ),
                    (
                        'EnglishHornStaffI',
                        [
                            abjad.Momento(
                                context='EnglishHornVoiceI',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='EnglishHornVoiceI',
                                prototype='abjad.Instrument',
                                value='EnglishHorn',
                                ),
                            abjad.Momento(
                                context='EnglishHornVoiceI',
                                prototype='abjad.MarginMarkup',
                                value='Eng. hn.',
                                ),
                            ],
                        ),
                    (
                        'EnglishHornVoiceI',
                        [
                            abjad.Momento(
                                context='EnglishHornVoiceI',
                                prototype='abjad.Dynamic',
                                value='niente',
                                ),
                            ],
                        ),
                    (
                        'FirstViolinStaffI',
                        [
                            abjad.Momento(
                                context='FirstViolinVoiceI',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='FirstViolinVoiceI',
                                prototype='abjad.Instrument',
                                value='Violin',
                                ),
                            abjad.Momento(
                                context='FirstViolinVoiceI',
                                prototype='abjad.MarginMarkup',
                                value='Vni. I (1-4) (5-8)',
                                ),
                            ],
                        ),
                    (
                        'FirstViolinStaffII',
                        [
                            abjad.Momento(
                                context='FirstViolinVoiceII',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='FirstViolinVoiceII',
                                prototype='abjad.Instrument',
                                value='Violin',
                                ),
                            abjad.Momento(
                                context='FirstViolinVoiceII',
                                prototype='abjad.MarginMarkup',
                                value='Vni. I (9-12) (13-17)',
                                ),
                            ],
                        ),
                    (
                        'FirstViolinStaffIII',
                        [
                            abjad.Momento(
                                context='FirstViolinVoiceV',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='FirstViolinVoiceV',
                                prototype='abjad.Instrument',
                                value='Violin',
                                ),
                            abjad.Momento(
                                context='FirstViolinVoiceV',
                                prototype='abjad.MarginMarkup',
                                value='Vni. I 18',
                                ),
                            ],
                        ),
                    (
                        'FirstViolinStaffIV',
                        [
                            abjad.Momento(
                                context='FirstViolinVoiceVII',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='FirstViolinVoiceVII',
                                prototype='abjad.Instrument',
                                value='Violin',
                                ),
                            abjad.Momento(
                                context='FirstViolinVoiceVII',
                                prototype='abjad.MarginMarkup',
                                value='Vni. I',
                                ),
                            ],
                        ),
                    (
                        'FirstViolinStaffIX',
                        [
                            abjad.Momento(
                                context='FirstViolinVoiceXVII',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='FirstViolinVoiceXVII',
                                prototype='abjad.Instrument',
                                value='Violin',
                                ),
                            abjad.Momento(
                                context='FirstViolinVoiceXVII',
                                prototype='abjad.MarginMarkup',
                                value='Vni. I',
                                ),
                            ],
                        ),
                    (
                        'FirstViolinStaffV',
                        [
                            abjad.Momento(
                                context='FirstViolinVoiceIX',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='FirstViolinVoiceIX',
                                prototype='abjad.Instrument',
                                value='Violin',
                                ),
                            abjad.Momento(
                                context='FirstViolinVoiceIX',
                                prototype='abjad.MarginMarkup',
                                value='Vni. I',
                                ),
                            ],
                        ),
                    (
                        'FirstViolinStaffVI',
                        [
                            abjad.Momento(
                                context='FirstViolinVoiceXI',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='FirstViolinVoiceXI',
                                prototype='abjad.Instrument',
                                value='Violin',
                                ),
                            abjad.Momento(
                                context='FirstViolinVoiceXI',
                                prototype='abjad.MarginMarkup',
                                value='Vni. I',
                                ),
                            ],
                        ),
                    (
                        'FirstViolinStaffVII',
                        [
                            abjad.Momento(
                                context='FirstViolinVoiceXIII',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='FirstViolinVoiceXIII',
                                prototype='abjad.Instrument',
                                value='Violin',
                                ),
                            abjad.Momento(
                                context='FirstViolinVoiceXIII',
                                prototype='abjad.MarginMarkup',
                                value='Vni. I',
                                ),
                            ],
                        ),
                    (
                        'FirstViolinStaffVIII',
                        [
                            abjad.Momento(
                                context='FirstViolinVoiceXV',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='FirstViolinVoiceXV',
                                prototype='abjad.Instrument',
                                value='Violin',
                                ),
                            abjad.Momento(
                                context='FirstViolinVoiceXV',
                                prototype='abjad.MarginMarkup',
                                value='Vni. I',
                                ),
                            ],
                        ),
                    (
                        'FirstViolinVoiceI',
                        [
                            abjad.Momento(
                                context='FirstViolinVoiceI',
                                prototype='abjad.Dynamic',
                                value='niente',
                                ),
                            ],
                        ),
                    (
                        'FirstViolinVoiceII',
                        [
                            abjad.Momento(
                                context='FirstViolinVoiceII',
                                prototype='abjad.Dynamic',
                                value='niente',
                                ),
                            ],
                        ),
                    (
                        'FirstViolinVoiceIII',
                        [
                            abjad.Momento(
                                context='FirstViolinVoiceIII',
                                prototype='abjad.Dynamic',
                                value='niente',
                                ),
                            ],
                        ),
                    (
                        'FirstViolinVoiceIV',
                        [
                            abjad.Momento(
                                context='FirstViolinVoiceIV',
                                prototype='abjad.Dynamic',
                                value='niente',
                                ),
                            ],
                        ),
                    (
                        'FirstViolinVoiceV',
                        [
                            abjad.Momento(
                                context='FirstViolinVoiceV',
                                prototype='abjad.Dynamic',
                                value='f',
                                ),
                            ],
                        ),
                    (
                        'FluteStaffI',
                        [
                            abjad.Momento(
                                context='FluteVoiceI',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='FluteVoiceIII',
                                prototype='abjad.Instrument',
                                value='Flute',
                                ),
                            abjad.Momento(
                                context='FluteVoiceI',
                                prototype='abjad.MarginMarkup',
                                value='Fl. (1+3)',
                                ),
                            ],
                        ),
                    (
                        'FluteStaffII',
                        [
                            abjad.Momento(
                                context='FluteVoiceII',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='FluteVoiceIV',
                                prototype='abjad.Instrument',
                                value='Flute',
                                ),
                            abjad.Momento(
                                context='FluteVoiceII',
                                prototype='abjad.MarginMarkup',
                                value='Fl. (2+4)',
                                ),
                            ],
                        ),
                    (
                        'FluteVoiceI',
                        [
                            abjad.Momento(
                                context='FluteVoiceI',
                                edition=abjad.Tag('+PARTS'),
                                prototype='abjad.Dynamic',
                                value='ff',
                                ),
                            ],
                        ),
                    (
                        'FluteVoiceII',
                        [
                            abjad.Momento(
                                context='FluteVoiceII',
                                edition=abjad.Tag('+PARTS'),
                                prototype='abjad.Dynamic',
                                value='ff',
                                ),
                            ],
                        ),
                    (
                        'FluteVoiceIII',
                        [
                            abjad.Momento(
                                context='FluteVoiceIII',
                                prototype='abjad.Dynamic',
                                value='ff',
                                ),
                            ],
                        ),
                    (
                        'FluteVoiceIV',
                        [
                            abjad.Momento(
                                context='FluteVoiceIV',
                                prototype='abjad.Dynamic',
                                value='ff',
                                ),
                            ],
                        ),
                    (
                        'HarpPianoStaff',
                        [
                            abjad.Momento(
                                context='HarpVoiceI',
                                prototype='abjad.Instrument',
                                value='Harp',
                                ),
                            ],
                        ),
                    (
                        'HarpStaffI',
                        [
                            abjad.Momento(
                                context='HarpVoiceI',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='HarpVoiceI',
                                prototype='abjad.MarginMarkup',
                                value='Hp.',
                                ),
                            ],
                        ),
                    (
                        'HarpVoiceI',
                        [
                            abjad.Momento(
                                context='HarpVoiceI',
                                prototype='abjad.Dynamic',
                                value='mf',
                                ),
                            ],
                        ),
                    (
                        'HornStaffI',
                        [
                            abjad.Momento(
                                context='HornVoiceI',
                                prototype='abjad.Clef',
                                value='bass',
                                ),
                            abjad.Momento(
                                context='HornVoiceIII',
                                prototype='abjad.Instrument',
                                value='Horn',
                                ),
                            abjad.Momento(
                                context='HornVoiceI',
                                prototype='abjad.MarginMarkup',
                                value='Hn. (1+3)',
                                ),
                            ],
                        ),
                    (
                        'HornStaffII',
                        [
                            abjad.Momento(
                                context='HornVoiceII',
                                prototype='abjad.Clef',
                                value='bass',
                                ),
                            abjad.Momento(
                                context='HornVoiceIV',
                                prototype='abjad.Instrument',
                                value='Horn',
                                ),
                            abjad.Momento(
                                context='HornVoiceII',
                                prototype='abjad.MarginMarkup',
                                value='Hn. (2+4)',
                                ),
                            ],
                        ),
                    (
                        'HornVoiceI',
                        [
                            abjad.Momento(
                                context='HornVoiceI',
                                edition=abjad.Tag('+PARTS'),
                                prototype='abjad.Dynamic',
                                value='sfz',
                                ),
                            ],
                        ),
                    (
                        'HornVoiceII',
                        [
                            abjad.Momento(
                                context='HornVoiceII',
                                edition=abjad.Tag('+PARTS'),
                                prototype='abjad.Dynamic',
                                value='sfz',
                                ),
                            ],
                        ),
                    (
                        'HornVoiceIII',
                        [
                            abjad.Momento(
                                context='HornVoiceIII',
                                prototype='abjad.Dynamic',
                                value='sfz',
                                ),
                            ],
                        ),
                    (
                        'HornVoiceIV',
                        [
                            abjad.Momento(
                                context='HornVoiceIV',
                                prototype='abjad.Dynamic',
                                value='sfz',
                                ),
                            ],
                        ),
                    (
                        'OboeStaffI',
                        [
                            abjad.Momento(
                                context='OboeVoiceI',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='OboeVoiceI',
                                prototype='abjad.Instrument',
                                value='Oboe',
                                ),
                            abjad.Momento(
                                context='OboeVoiceI',
                                prototype='abjad.MarginMarkup',
                                value='Ob.',
                                ),
                            ],
                        ),
                    (
                        'OboeVoiceI',
                        [
                            abjad.Momento(
                                context='OboeVoiceI',
                                prototype='abjad.Dynamic',
                                value='niente',
                                ),
                            ],
                        ),
                    (
                        'PercussionStaffI',
                        [
                            abjad.Momento(
                                context='PercussionVoiceI',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceI',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceI',
                                prototype='abjad.MarginMarkup',
                                value='Perc. 1 (tri.)',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceI',
                                prototype='abjad.PersistentOverride',
                                value=abjad.PersistentOverride(
                                    after=True,
                                    attribute='bar_extent',
                                    context='Staff',
                                    grob='bar_line',
                                    value=(0, 0),
                                    ),
                                ),
                            abjad.Momento(
                                context='PercussionVoiceI',
                                prototype='baca.StaffLines',
                                value=1,
                                ),
                            ],
                        ),
                    (
                        'PercussionStaffII',
                        [
                            abjad.Momento(
                                context='PercussionVoiceII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceII',
                                prototype='abjad.MarginMarkup',
                                value='Perc. 2 (cym.)',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceII',
                                prototype='abjad.PersistentOverride',
                                value=abjad.PersistentOverride(
                                    after=True,
                                    attribute='bar_extent',
                                    context='Staff',
                                    grob='bar_line',
                                    value=(0, 0),
                                    ),
                                ),
                            abjad.Momento(
                                context='PercussionVoiceII',
                                prototype='baca.StaffLines',
                                value=1,
                                ),
                            ],
                        ),
                    (
                        'PercussionStaffIII',
                        [
                            abjad.Momento(
                                context='PercussionVoiceIII',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceIII',
                                prototype='abjad.Instrument',
                                value='Vibraphone',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceIII',
                                prototype='abjad.MarginMarkup',
                                value='Perc. 3 (vib.)',
                                ),
                            ],
                        ),
                    (
                        'PercussionVoiceI',
                        [
                            abjad.Momento(
                                context='PercussionVoiceI',
                                prototype='abjad.Dynamic',
                                value='mp',
                                ),
                            ],
                        ),
                    (
                        'PercussionVoiceII',
                        [
                            abjad.Momento(
                                context='PercussionVoiceII',
                                prototype='abjad.Dynamic',
                                value='mp',
                                ),
                            ],
                        ),
                    (
                        'PercussionVoiceIII',
                        [
                            abjad.Momento(
                                context='PercussionVoiceIII',
                                prototype='abjad.Dynamic',
                                value='mp',
                                ),
                            ],
                        ),
                    (
                        'PianoPianoStaff',
                        [
                            abjad.Momento(
                                context='PianoVoiceI',
                                prototype='abjad.Instrument',
                                value='Piano',
                                ),
                            ],
                        ),
                    (
                        'PianoStaffI',
                        [
                            abjad.Momento(
                                context='PianoVoiceI',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='PianoVoiceI',
                                prototype='abjad.MarginMarkup',
                                value='Pf.',
                                ),
                            ],
                        ),
                    (
                        'PianoVoiceI',
                        [
                            abjad.Momento(
                                context='PianoVoiceI',
                                prototype='abjad.Dynamic',
                                value='mf',
                                ),
                            ],
                        ),
                    (
                        'Score',
                        [
                            abjad.Momento(
                                context='GlobalSkips',
                                prototype='abjad.MetronomeMark',
                                value='76',
                                ),
                            abjad.Momento(
                                context='GlobalSkips',
                                prototype='abjad.TimeSignature',
                                value='4/4',
                                ),
                            ],
                        ),
                    (
                        'SecondViolinStaffI',
                        [
                            abjad.Momento(
                                context='SecondViolinVoiceI',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='SecondViolinVoiceI',
                                prototype='abjad.Instrument',
                                value='Violin',
                                ),
                            abjad.Momento(
                                context='SecondViolinVoiceI',
                                prototype='abjad.MarginMarkup',
                                value='Vni. II (1-4) (5-8)',
                                ),
                            ],
                        ),
                    (
                        'SecondViolinStaffII',
                        [
                            abjad.Momento(
                                context='SecondViolinVoiceII',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='SecondViolinVoiceII',
                                prototype='abjad.Instrument',
                                value='Violin',
                                ),
                            abjad.Momento(
                                context='SecondViolinVoiceII',
                                prototype='abjad.MarginMarkup',
                                value='Vni. II (9-12) (13-18)',
                                ),
                            ],
                        ),
                    (
                        'SecondViolinStaffIII',
                        [
                            abjad.Momento(
                                context='SecondViolinVoiceV',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='SecondViolinVoiceV',
                                prototype='abjad.Instrument',
                                value='Violin',
                                ),
                            abjad.Momento(
                                context='SecondViolinVoiceV',
                                prototype='abjad.MarginMarkup',
                                value='Vni. II',
                                ),
                            ],
                        ),
                    (
                        'SecondViolinStaffIV',
                        [
                            abjad.Momento(
                                context='SecondViolinVoiceVII',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='SecondViolinVoiceVII',
                                prototype='abjad.Instrument',
                                value='Violin',
                                ),
                            abjad.Momento(
                                context='SecondViolinVoiceVII',
                                prototype='abjad.MarginMarkup',
                                value='Vni. II',
                                ),
                            ],
                        ),
                    (
                        'SecondViolinStaffIX',
                        [
                            abjad.Momento(
                                context='SecondViolinVoiceXVII',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='SecondViolinVoiceXVII',
                                prototype='abjad.Instrument',
                                value='Violin',
                                ),
                            abjad.Momento(
                                context='SecondViolinVoiceXVII',
                                prototype='abjad.MarginMarkup',
                                value='Vni. II',
                                ),
                            ],
                        ),
                    (
                        'SecondViolinStaffV',
                        [
                            abjad.Momento(
                                context='SecondViolinVoiceIX',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='SecondViolinVoiceIX',
                                prototype='abjad.Instrument',
                                value='Violin',
                                ),
                            abjad.Momento(
                                context='SecondViolinVoiceIX',
                                prototype='abjad.MarginMarkup',
                                value='Vni. II',
                                ),
                            ],
                        ),
                    (
                        'SecondViolinStaffVI',
                        [
                            abjad.Momento(
                                context='SecondViolinVoiceXI',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='SecondViolinVoiceXI',
                                prototype='abjad.Instrument',
                                value='Violin',
                                ),
                            abjad.Momento(
                                context='SecondViolinVoiceXI',
                                prototype='abjad.MarginMarkup',
                                value='Vni. II',
                                ),
                            ],
                        ),
                    (
                        'SecondViolinStaffVII',
                        [
                            abjad.Momento(
                                context='SecondViolinVoiceXIII',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='SecondViolinVoiceXIII',
                                prototype='abjad.Instrument',
                                value='Violin',
                                ),
                            abjad.Momento(
                                context='SecondViolinVoiceXIII',
                                prototype='abjad.MarginMarkup',
                                value='Vni. II',
                                ),
                            ],
                        ),
                    (
                        'SecondViolinStaffVIII',
                        [
                            abjad.Momento(
                                context='SecondViolinVoiceXV',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='SecondViolinVoiceXV',
                                prototype='abjad.Instrument',
                                value='Violin',
                                ),
                            abjad.Momento(
                                context='SecondViolinVoiceXV',
                                prototype='abjad.MarginMarkup',
                                value='Vni. II',
                                ),
                            ],
                        ),
                    (
                        'SecondViolinVoiceI',
                        [
                            abjad.Momento(
                                context='SecondViolinVoiceI',
                                prototype='abjad.Dynamic',
                                value='niente',
                                ),
                            ],
                        ),
                    (
                        'SecondViolinVoiceII',
                        [
                            abjad.Momento(
                                context='SecondViolinVoiceII',
                                prototype='abjad.Dynamic',
                                value='niente',
                                ),
                            ],
                        ),
                    (
                        'SecondViolinVoiceIII',
                        [
                            abjad.Momento(
                                context='SecondViolinVoiceIII',
                                prototype='abjad.Dynamic',
                                value='niente',
                                ),
                            ],
                        ),
                    (
                        'SecondViolinVoiceIV',
                        [
                            abjad.Momento(
                                context='SecondViolinVoiceIV',
                                prototype='abjad.Dynamic',
                                value='niente',
                                ),
                            ],
                        ),
                    (
                        'TromboneStaffI',
                        [
                            abjad.Momento(
                                context='TromboneVoiceI',
                                prototype='abjad.Clef',
                                value='tenor',
                                ),
                            abjad.Momento(
                                context='TromboneVoiceIII',
                                prototype='abjad.Instrument',
                                value='Trombone',
                                ),
                            abjad.Momento(
                                context='TromboneVoiceI',
                                prototype='abjad.MarginMarkup',
                                value='Trb. (1+3)',
                                ),
                            ],
                        ),
                    (
                        'TromboneStaffII',
                        [
                            abjad.Momento(
                                context='TromboneVoiceII',
                                prototype='abjad.Clef',
                                value='tenor',
                                ),
                            abjad.Momento(
                                context='TromboneVoiceIV',
                                prototype='abjad.Instrument',
                                value='Trombone',
                                ),
                            abjad.Momento(
                                context='TromboneVoiceII',
                                prototype='abjad.MarginMarkup',
                                value='Trb. (2+4)',
                                ),
                            ],
                        ),
                    (
                        'TromboneVoiceI',
                        [
                            abjad.Momento(
                                context='TromboneVoiceI',
                                edition=abjad.Tag('+PARTS'),
                                prototype='abjad.Dynamic',
                                value='sfz',
                                ),
                            ],
                        ),
                    (
                        'TromboneVoiceII',
                        [
                            abjad.Momento(
                                context='TromboneVoiceII',
                                edition=abjad.Tag('+PARTS'),
                                prototype='abjad.Dynamic',
                                value='sfz',
                                ),
                            ],
                        ),
                    (
                        'TromboneVoiceIII',
                        [
                            abjad.Momento(
                                context='TromboneVoiceIII',
                                prototype='abjad.Dynamic',
                                value='sfz',
                                ),
                            ],
                        ),
                    (
                        'TromboneVoiceIV',
                        [
                            abjad.Momento(
                                context='TromboneVoiceIV',
                                prototype='abjad.Dynamic',
                                value='sfz',
                                ),
                            ],
                        ),
                    (
                        'TrumpetStaffI',
                        [
                            abjad.Momento(
                                context='TrumpetVoiceI',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='TrumpetVoiceIII',
                                prototype='abjad.Instrument',
                                value='Trumpet',
                                ),
                            abjad.Momento(
                                context='TrumpetVoiceI',
                                prototype='abjad.MarginMarkup',
                                value='Tp. (1+3)',
                                ),
                            ],
                        ),
                    (
                        'TrumpetStaffII',
                        [
                            abjad.Momento(
                                context='TrumpetVoiceII',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='TrumpetVoiceIV',
                                prototype='abjad.Instrument',
                                value='Trumpet',
                                ),
                            abjad.Momento(
                                context='TrumpetVoiceII',
                                prototype='abjad.MarginMarkup',
                                value='Tp. (2+4)',
                                ),
                            ],
                        ),
                    (
                        'TrumpetVoiceI',
                        [
                            abjad.Momento(
                                context='TrumpetVoiceI',
                                edition=abjad.Tag('+PARTS'),
                                prototype='abjad.Dynamic',
                                value='sfz',
                                ),
                            ],
                        ),
                    (
                        'TrumpetVoiceII',
                        [
                            abjad.Momento(
                                context='TrumpetVoiceII',
                                edition=abjad.Tag('+PARTS'),
                                prototype='abjad.Dynamic',
                                value='sfz',
                                ),
                            ],
                        ),
                    (
                        'TrumpetVoiceIII',
                        [
                            abjad.Momento(
                                context='TrumpetVoiceIII',
                                prototype='abjad.Dynamic',
                                value='sfz',
                                ),
                            ],
                        ),
                    (
                        'TrumpetVoiceIV',
                        [
                            abjad.Momento(
                                context='TrumpetVoiceIV',
                                prototype='abjad.Dynamic',
                                value='sfz',
                                ),
                            ],
                        ),
                    (
                        'TubaStaffI',
                        [
                            abjad.Momento(
                                context='TubaVoiceI',
                                prototype='abjad.Clef',
                                value='bass',
                                ),
                            abjad.Momento(
                                context='TubaVoiceI',
                                prototype='abjad.Instrument',
                                value='Tuba',
                                ),
                            abjad.Momento(
                                context='TubaVoiceI',
                                prototype='abjad.MarginMarkup',
                                value='Tub.',
                                ),
                            ],
                        ),
                    (
                        'TubaVoiceI',
                        [
                            abjad.Momento(
                                context='TubaVoiceI',
                                prototype='abjad.Dynamic',
                                value='sffz',
                                ),
                            ],
                        ),
                    (
                        'ViolaStaffI',
                        [
                            abjad.Momento(
                                context='ViolaVoiceI',
                                prototype='abjad.Clef',
                                value='alto',
                                ),
                            abjad.Momento(
                                context='ViolaVoiceI',
                                prototype='abjad.Instrument',
                                value='Viola',
                                ),
                            abjad.Momento(
                                context='ViolaVoiceI',
                                prototype='abjad.MarginMarkup',
                                value='Vle. (1-4) (5-8)',
                                ),
                            ],
                        ),
                    (
                        'ViolaStaffII',
                        [
                            abjad.Momento(
                                context='ViolaVoiceII',
                                prototype='abjad.Clef',
                                value='alto',
                                ),
                            abjad.Momento(
                                context='ViolaVoiceII',
                                prototype='abjad.Instrument',
                                value='Viola',
                                ),
                            abjad.Momento(
                                context='ViolaVoiceII',
                                prototype='abjad.MarginMarkup',
                                value='Vle. (9-12) (13-18)',
                                ),
                            ],
                        ),
                    (
                        'ViolaStaffIII',
                        [
                            abjad.Momento(
                                context='ViolaVoiceV',
                                prototype='abjad.Clef',
                                value='alto',
                                ),
                            abjad.Momento(
                                context='ViolaVoiceV',
                                prototype='abjad.Instrument',
                                value='Viola',
                                ),
                            abjad.Momento(
                                context='ViolaVoiceV',
                                prototype='abjad.MarginMarkup',
                                value='Vle.',
                                ),
                            ],
                        ),
                    (
                        'ViolaStaffIV',
                        [
                            abjad.Momento(
                                context='ViolaVoiceVII',
                                prototype='abjad.Clef',
                                value='alto',
                                ),
                            abjad.Momento(
                                context='ViolaVoiceVII',
                                prototype='abjad.Instrument',
                                value='Viola',
                                ),
                            abjad.Momento(
                                context='ViolaVoiceVII',
                                prototype='abjad.MarginMarkup',
                                value='Vle.',
                                ),
                            ],
                        ),
                    (
                        'ViolaStaffIX',
                        [
                            abjad.Momento(
                                context='ViolaVoiceXVII',
                                prototype='abjad.Clef',
                                value='alto',
                                ),
                            abjad.Momento(
                                context='ViolaVoiceXVII',
                                prototype='abjad.Instrument',
                                value='Viola',
                                ),
                            abjad.Momento(
                                context='ViolaVoiceXVII',
                                prototype='abjad.MarginMarkup',
                                value='Vle.',
                                ),
                            ],
                        ),
                    (
                        'ViolaStaffV',
                        [
                            abjad.Momento(
                                context='ViolaVoiceIX',
                                prototype='abjad.Clef',
                                value='alto',
                                ),
                            abjad.Momento(
                                context='ViolaVoiceIX',
                                prototype='abjad.Instrument',
                                value='Viola',
                                ),
                            abjad.Momento(
                                context='ViolaVoiceIX',
                                prototype='abjad.MarginMarkup',
                                value='Vle.',
                                ),
                            ],
                        ),
                    (
                        'ViolaStaffVI',
                        [
                            abjad.Momento(
                                context='ViolaVoiceXI',
                                prototype='abjad.Clef',
                                value='alto',
                                ),
                            abjad.Momento(
                                context='ViolaVoiceXI',
                                prototype='abjad.Instrument',
                                value='Viola',
                                ),
                            abjad.Momento(
                                context='ViolaVoiceXI',
                                prototype='abjad.MarginMarkup',
                                value='Vle.',
                                ),
                            ],
                        ),
                    (
                        'ViolaStaffVII',
                        [
                            abjad.Momento(
                                context='ViolaVoiceXIII',
                                prototype='abjad.Clef',
                                value='alto',
                                ),
                            abjad.Momento(
                                context='ViolaVoiceXIII',
                                prototype='abjad.Instrument',
                                value='Viola',
                                ),
                            abjad.Momento(
                                context='ViolaVoiceXIII',
                                prototype='abjad.MarginMarkup',
                                value='Vle.',
                                ),
                            ],
                        ),
                    (
                        'ViolaStaffVIII',
                        [
                            abjad.Momento(
                                context='ViolaVoiceXV',
                                prototype='abjad.Clef',
                                value='alto',
                                ),
                            abjad.Momento(
                                context='ViolaVoiceXV',
                                prototype='abjad.Instrument',
                                value='Viola',
                                ),
                            abjad.Momento(
                                context='ViolaVoiceXV',
                                prototype='abjad.MarginMarkup',
                                value='Vle.',
                                ),
                            ],
                        ),
                    (
                        'ViolaVoiceI',
                        [
                            abjad.Momento(
                                context='ViolaVoiceI',
                                prototype='abjad.Dynamic',
                                value='niente',
                                ),
                            ],
                        ),
                    (
                        'ViolaVoiceII',
                        [
                            abjad.Momento(
                                context='ViolaVoiceII',
                                prototype='abjad.Dynamic',
                                value='niente',
                                ),
                            ],
                        ),
                    (
                        'ViolaVoiceIII',
                        [
                            abjad.Momento(
                                context='ViolaVoiceIII',
                                prototype='abjad.Dynamic',
                                value='niente',
                                ),
                            ],
                        ),
                    (
                        'ViolaVoiceIV',
                        [
                            abjad.Momento(
                                context='ViolaVoiceIV',
                                prototype='abjad.Dynamic',
                                value='niente',
                                ),
                            ],
                        ),
                    ]
                ),
            ),
        ('segment_name', 'O1'),
        ('segment_number', 20),
        (
            'sounds_during_segment',
            abjad.OrderedDict(
                [
                    ('CelloVoiceI', False),
                    ('CelloVoiceII', False),
                    ('CelloVoiceIII', False),
                    ('CelloVoiceIV', False),
                    ('CelloVoiceIX', False),
                    ('CelloVoiceV', False),
                    ('CelloVoiceVI', False),
                    ('CelloVoiceVII', False),
                    ('CelloVoiceVIII', False),
                    ('CelloVoiceX', False),
                    ('CelloVoiceXI', False),
                    ('CelloVoiceXII', False),
                    ('CelloVoiceXIII', False),
                    ('CelloVoiceXIV', False),
                    ('ContrabassVoiceI', True),
                    ('ContrabassVoiceII', True),
                    ('ContrabassVoiceIII', True),
                    ('ContrabassVoiceIV', True),
                    ('ContrabassVoiceV', True),
                    ('ContrabassVoiceVI', True),
                    ('FirstViolinVoiceI', False),
                    ('FirstViolinVoiceII', False),
                    ('FirstViolinVoiceIII', False),
                    ('FirstViolinVoiceIV', False),
                    ('FirstViolinVoiceIX', False),
                    ('FirstViolinVoiceV', False),
                    ('FirstViolinVoiceVI', False),
                    ('FirstViolinVoiceVII', False),
                    ('FirstViolinVoiceVIII', False),
                    ('FirstViolinVoiceX', False),
                    ('FirstViolinVoiceXI', False),
                    ('FirstViolinVoiceXII', False),
                    ('FirstViolinVoiceXIII', False),
                    ('FirstViolinVoiceXIV', False),
                    ('FirstViolinVoiceXV', False),
                    ('FirstViolinVoiceXVI', False),
                    ('FirstViolinVoiceXVII', False),
                    ('FirstViolinVoiceXVIII', False),
                    ('SecondViolinVoiceI', False),
                    ('SecondViolinVoiceII', False),
                    ('SecondViolinVoiceIII', False),
                    ('SecondViolinVoiceIV', False),
                    ('SecondViolinVoiceIX', False),
                    ('SecondViolinVoiceV', False),
                    ('SecondViolinVoiceVI', False),
                    ('SecondViolinVoiceVII', False),
                    ('SecondViolinVoiceVIII', False),
                    ('SecondViolinVoiceX', False),
                    ('SecondViolinVoiceXI', False),
                    ('SecondViolinVoiceXII', False),
                    ('SecondViolinVoiceXIII', False),
                    ('SecondViolinVoiceXIV', False),
                    ('SecondViolinVoiceXV', False),
                    ('SecondViolinVoiceXVI', False),
                    ('SecondViolinVoiceXVII', False),
                    ('SecondViolinVoiceXVIII', False),
                    ('ViolaVoiceI', False),
                    ('ViolaVoiceII', False),
                    ('ViolaVoiceIII', False),
                    ('ViolaVoiceIV', False),
                    ('ViolaVoiceIX', False),
                    ('ViolaVoiceV', False),
                    ('ViolaVoiceVI', False),
                    ('ViolaVoiceVII', False),
                    ('ViolaVoiceVIII', False),
                    ('ViolaVoiceX', False),
                    ('ViolaVoiceXI', False),
                    ('ViolaVoiceXII', False),
                    ('ViolaVoiceXIII', False),
                    ('ViolaVoiceXIV', False),
                    ('ViolaVoiceXV', False),
                    ('ViolaVoiceXVI', False),
                    ('ViolaVoiceXVII', False),
                    ('ViolaVoiceXVIII', False),
                    ]
                ),
            ),
        ('start_clock_time', "4'18''"),
        ('stop_clock_time', "4'29''"),
        (
            'time_signatures',
            ['4/4', '2/4', '4/4', '4/4'],
            ),
        (
            'voice_metadata',
            abjad.OrderedDict(
                [
                    (
                        'ContrabassVoiceI',
                        abjad.OrderedDict(
                            [
                                (
                                    'RHYTHM',
                                    abjad.OrderedDict(
                                        [
                                            ('divisions_consumed', 14),
                                            ('logical_ties_produced', 17),
                                            ('name', 'clb_rhythm'),
                                            ('talea_weight_consumed', 56),
                                            ]
                                        ),
                                    ),
                                ]
                            ),
                        ),
                    (
                        'ContrabassVoiceII',
                        abjad.OrderedDict(
                            [
                                (
                                    'RHYTHM',
                                    abjad.OrderedDict(
                                        [
                                            ('divisions_consumed', 14),
                                            ('logical_ties_produced', 17),
                                            ('name', 'clb_rhythm'),
                                            ('talea_weight_consumed', 56),
                                            ]
                                        ),
                                    ),
                                ]
                            ),
                        ),
                    (
                        'ContrabassVoiceIII',
                        abjad.OrderedDict(
                            [
                                (
                                    'RHYTHM',
                                    abjad.OrderedDict(
                                        [
                                            ('divisions_consumed', 14),
                                            ('logical_ties_produced', 17),
                                            ('name', 'clb_rhythm'),
                                            ('talea_weight_consumed', 56),
                                            ]
                                        ),
                                    ),
                                ]
                            ),
                        ),
                    (
                        'ContrabassVoiceIV',
                        abjad.OrderedDict(
                            [
                                (
                                    'RHYTHM',
                                    abjad.OrderedDict(
                                        [
                                            ('divisions_consumed', 14),
                                            ('logical_ties_produced', 17),
                                            ('name', 'clb_rhythm'),
                                            ('talea_weight_consumed', 56),
                                            ]
                                        ),
                                    ),
                                ]
                            ),
                        ),
                    (
                        'ContrabassVoiceV',
                        abjad.OrderedDict(
                            [
                                (
                                    'RHYTHM',
                                    abjad.OrderedDict(
                                        [
                                            ('divisions_consumed', 14),
                                            ('logical_ties_produced', 17),
                                            ('name', 'clb_rhythm'),
                                            ('talea_weight_consumed', 56),
                                            ]
                                        ),
                                    ),
                                ]
                            ),
                        ),
                    (
                        'ContrabassVoiceVI',
                        abjad.OrderedDict(
                            [
                                (
                                    'RHYTHM',
                                    abjad.OrderedDict(
                                        [
                                            ('divisions_consumed', 14),
                                            ('logical_ties_produced', 17),
                                            ('name', 'clb_rhythm'),
                                            ('talea_weight_consumed', 56),
                                            ]
                                        ),
                                    ),
                                ]
                            ),
                        ),
                    ]
                ),
            ),
        ]
    )
