import abjad


metadata = abjad.OrderedDict(
    [
        (
            'bol_measure_numbers',
            [1],
            ),
        ('duration', "0'11''"),
        ('first_measure_number', 1),
        ('last_measure_number', 6),
        (
            'persistent_indicators',
            abjad.OrderedDict(
                [
                    (
                        'CellosStaffI',
                        [
                            abjad.Momento(
                                context='CellosVoiceI',
                                prototype='abjad.Clef',
                                value='tenor',
                                ),
                            abjad.Momento(
                                context='CellosVoiceI',
                                prototype='abjad.Instrument',
                                value='Cello',
                                ),
                            abjad.Momento(
                                context='CellosVoiceI',
                                prototype='baca.MarginMarkup',
                                value='Vc.',
                                ),
                            ],
                        ),
                    (
                        'CellosVoiceI',
                        [
                            abjad.Momento(
                                context='CellosVoiceI',
                                prototype='abjad.Dynamic',
                                value='\\p_sub_accents_continue_sffz',
                                ),
                            ],
                        ),
                    (
                        'FirstViolinsStaffI',
                        [
                            abjad.Momento(
                                context='FirstViolinsVoiceI',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='FirstViolinsVoiceI',
                                prototype='abjad.Instrument',
                                value='Violin',
                                ),
                            abjad.Momento(
                                context='FirstViolinsVoiceI',
                                prototype='baca.MarginMarkup',
                                value='Vni. I',
                                ),
                            ],
                        ),
                    (
                        'FirstViolinsStaffII',
                        [
                            abjad.Momento(
                                context='FirstViolinsVoiceII',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='FirstViolinsVoiceII',
                                prototype='abjad.Instrument',
                                value='Violin',
                                ),
                            abjad.Momento(
                                context='FirstViolinsVoiceII',
                                prototype='baca.MarginMarkup',
                                value='Vni. I',
                                ),
                            ],
                        ),
                    (
                        'FirstViolinsVoiceI',
                        [
                            abjad.Momento(
                                context='FirstViolinsVoiceI',
                                prototype='abjad.Dynamic',
                                value='\\p_sub_accents_continue_sffz',
                                ),
                            ],
                        ),
                    (
                        'FirstViolinsVoiceII',
                        [
                            abjad.Momento(
                                context='FirstViolinsVoiceII',
                                prototype='abjad.Dynamic',
                                value='\\p_sub_accents_continue_sffz',
                                ),
                            ],
                        ),
                    (
                        'Score',
                        [
                            abjad.Momento(
                                context='GlobalSkips',
                                prototype='abjad.MetronomeMark',
                                value='114',
                                ),
                            abjad.Momento(
                                context='GlobalSkips',
                                prototype='abjad.TimeSignature',
                                value='4/4',
                                ),
                            ],
                        ),
                    (
                        'SecondViolinsStaffI',
                        [
                            abjad.Momento(
                                context='SecondViolinsVoiceI',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='SecondViolinsVoiceI',
                                prototype='abjad.Instrument',
                                value='Violin',
                                ),
                            abjad.Momento(
                                context='SecondViolinsVoiceI',
                                prototype='baca.MarginMarkup',
                                value='Vni. II',
                                ),
                            ],
                        ),
                    (
                        'SecondViolinsStaffII',
                        [
                            abjad.Momento(
                                context='SecondViolinsVoiceII',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='SecondViolinsVoiceII',
                                prototype='abjad.Instrument',
                                value='Violin',
                                ),
                            abjad.Momento(
                                context='SecondViolinsVoiceII',
                                prototype='baca.MarginMarkup',
                                value='Vni. II',
                                ),
                            ],
                        ),
                    (
                        'SecondViolinsVoiceI',
                        [
                            abjad.Momento(
                                context='SecondViolinsVoiceI',
                                prototype='abjad.Dynamic',
                                value='\\p_sub_accents_continue_sffz',
                                ),
                            ],
                        ),
                    (
                        'SecondViolinsVoiceII',
                        [
                            abjad.Momento(
                                context='SecondViolinsVoiceII',
                                prototype='abjad.Dynamic',
                                value='\\p_sub_accents_continue_sffz',
                                ),
                            ],
                        ),
                    (
                        'ViolasStaffI',
                        [
                            abjad.Momento(
                                context='ViolasVoiceI',
                                prototype='abjad.Clef',
                                value='alto',
                                ),
                            abjad.Momento(
                                context='ViolasVoiceI',
                                prototype='abjad.Instrument',
                                value='Viola',
                                ),
                            abjad.Momento(
                                context='ViolasVoiceI',
                                prototype='baca.MarginMarkup',
                                value='Vle.',
                                ),
                            ],
                        ),
                    (
                        'ViolasStaffII',
                        [
                            abjad.Momento(
                                context='ViolasVoiceII',
                                prototype='abjad.Clef',
                                value='alto',
                                ),
                            abjad.Momento(
                                context='ViolasVoiceII',
                                prototype='abjad.Instrument',
                                value='Viola',
                                ),
                            abjad.Momento(
                                context='ViolasVoiceII',
                                prototype='baca.MarginMarkup',
                                value='Vle.',
                                ),
                            ],
                        ),
                    (
                        'ViolasVoiceI',
                        [
                            abjad.Momento(
                                context='ViolasVoiceI',
                                prototype='abjad.Dynamic',
                                value='\\p_sub_accents_continue_sffz',
                                ),
                            ],
                        ),
                    (
                        'ViolasVoiceII',
                        [
                            abjad.Momento(
                                context='ViolasVoiceII',
                                prototype='abjad.Dynamic',
                                value='\\p_sub_accents_continue_sffz',
                                ),
                            ],
                        ),
                    ]
                ),
            ),
        ('segment_number', 1),
        ('start_clock_time', "0'00''"),
        ('stop_clock_time', "0'11''"),
        (
            'time_signatures',
            ['4/4', '4/4', '4/4', '3/4', '3/4', '4/4'],
            ),
        ]
    )
